### ISSUE TITLE
Feature request: send unformatted message from Logback

### ISSUE THREAD

**Issue by trueinsider** [mp911de/logstash-gelf#103]
Hi,

It would be great if I could include into GELF message field with unformatted message from Logback's ILoggingEvent.

**Comment by mp911de** [comment]
Should be a trivial enhancement since almost all logging frameworks have some specific fields that can be defined with [LogMessageField](https://github.com/mp911de/logstash-gelf/blob/master/src/main/java/biz/paluch/logging/gelf/LogMessageField.java). Maybe you want to submit a PR?

**Comment by cchet** [comment]
Is this still an issue  would like to help out?

**Comment by mp911de** [comment]
Yeah, I think that's a small change and it is limited to Logback.

**Comment by mp911de** [comment]
Closing as this ticket was open for a very long time without actual activity. We couldn't convince ourselves to implement it.
