### ISSUE TITLE
log4j2 - logstash-gelf configuration

### ISSUE THREAD

**Issue by DaveTaboola** [mp911de/logstash-gelf#105]
Hi 
I've search over the net but couldn't find anything that answer the case

I'm building java application thats using logstash-gelf in the log4j2 appenders.
The application is deployed over docker containers 
Thinking how to make the logging to actually make sense, i had in mind not using the log-drive of the docker, but sending log events from the application.

Is there a way to pass system variables to additional fields in the gelf configuration? 
I'd like to append couple of the container attributes.
(By the way i think it will really make the module popular, as people are looking for the best way to send docker logs to ES, specially java app logs) ?

If you have a different idea im more than happy to listen

**Comment by mp911de** [comment]
logstash-gelf is a plugin to log4j, log4j2 and other logging frameworks. It's configured through the configuration mechanisms provided by your log framework. 

For log4j2, the most common approach is using XML although it supports other configuration types. log4j2 can resolve property variables and look up configuration from the environment (see https://logging.apache.org/log4j/2.0/manual/lookups.html). You can use environment lookup with logstash-gelf's configuration elements available in the log4j2 configuration (see http://logging.paluch.biz/examples/log4j-2.x.html).

Passing environment variables into containers seems one of the more common configuration approaches with Docker.

**Comment by DaveTaboola** [comment]
Thank you very much Mark! 
(Plus its a good opportunity to say you're doing a great job with the plugin, so thanks for that as well)
