### ISSUE TITLE
Feature request: Allow the exclusion of message parameters from WildFlyJsonFormatter output

### ISSUE THREAD

**Issue by alberto-brigandi** [mp911de/logstash-gelf#106]
Currently (v1.11.0) there is no way to exclude the message parameters when using just the `WildFlyJsonFormatter`, as the `includeLogMessageParameters` property is not recognized

**Comment by mp911de** [comment]
Feel free to submit a PR.

**Comment by mp911de** [comment]
Fixed with #142
