### ISSUE TITLE
Keep throwing AlreadyClosedConnection

### ISSUE THREAD

**Issue by chainkite** [mp911de/logstash-gelf#107]
In v1.11.0, log4j2 GelfTcpSender

After a period without log, the tcp connection broke without reconnecting. All log after that will get the error below.
The tcp connection will reconnect in v1.10.0, but keep throwing error in v1.11.0
```
2017-02-04 23:56:10,996 Log4j2-AsyncLoggerConfig-2 ERROR Could not send GELF message: null
```

This error is thrown from [GelfTCPSender](https://github.com/mp911de/logstash-gelf/blob/a7a8225ec063031da59596840341d166700bc591/src/main/java/biz/paluch/logging/gelf/intern/sender/GelfTCPSender.java#L103), caused by `sun.nio.ch.SocketChannelImpl.ensureOpenAndUnconnected()` (AlreadyClosedConnection)

These two methods checking channel connectivity are inequal.
* [biz.paluch.logging.gelf.intern.sender.GelfTCPSender.isConnected()](https://github.com/mp911de/logstash-gelf/blob/a7a8225ec063031da59596840341d166700bc591/src/main/java/biz/paluch/logging/gelf/intern/sender/GelfTCPSender.java#L101)
* `sun.nio.ch.SocketChannelImpl.ensureOpenAndUnconnected()`

Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/mp911de/logstash-gelf/blob/master/.github/CONTRIBUTING.md).
- [x] You specify the logstash-gelf version and environment so it's obvious which version is affected
- [ ] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

**Comment by Linuem** [comment]
Same here.

**Comment by mp911de** [comment]
I pushed a fix for that issue to `master`. Care to give the fix a try?

**Comment by andrey-chernyshev** [comment]
Yes, now it seems to be recovering correctly. Thanks!!
