### ISSUE TITLE
Feature request: client certificate authentication

### ISSUE THREAD

**Issue by rbjorklin** [mp911de/logstash-gelf#108]
First off, big thanks for adding ssl support in #95!

A nice addition would be if there was support for client certificate authentication.

Logback has support for this with it's built-in SSLSocketAppender and it would be a nice feature to have with the logstash-gelf appender.

For reference: https://logback.qos.ch/manual/usingSSL.html

**Comment by mp911de** [comment]
That should work out of the box by setting the appropriate system properties, see http://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/JSSERefGuide.html#Customization

If you require customization beyond what's possible with system properties, then you can provide a custom [`GelfSenderProvider`](https://github.com/mp911de/logstash-gelf/blob/master/src/main/java/biz/paluch/logging/gelf/intern/GelfSenderProvider.java#L12-L12) that creates a new [`GelfTCPSSLSender`](https://github.com/mp911de/logstash-gelf/blob/master/src/main/java/biz/paluch/logging/gelf/intern/sender/GelfTCPSSLSender.java#L43-L43) with a customized `SSLContext`.

**Comment by rbjorklin** [comment]
You're so very right... I wasn't paying attention and didn't use the fully qualified properties. I.E. I was using `-DkeyStore=` when I should have been using `-Djavax.net.ssl.keyStore=`.

Thanks!
