### ISSUE TITLE
library should also accept status code 201

### ISSUE THREAD

**Issue by madmuffin1** [mp911de/logstash-gelf#114]
Hi,

we're happily using this library to send our logs to a managed logging service using HTTP. This logging service apparently implemented the HTTP receipt of the message differently than this library expects it.

This library requires the HTTP service to respond with a 202 (see [biz.paluch.logging.gelf.intern.sender.GelfHTTPSender#L63](https://github.com/mp911de/logstash-gelf/blob/a7a8225ec063031da59596840341d166700bc591/src/main/java/biz/paluch/logging/gelf/intern/sender/GelfHTTPSender.java#L63),) but they send a 201 CREATED.

As it is a managed service, we cannot change its behavior. Actually everything is working ok, but logstash-gelf kind of spams our logs, these two lines will be produced for _every single_ log message sent:

    14:14:53,747 |-ERROR in biz.paluch.logging.gelf.logback.GelfLogbackAppender[GELF] - Server responded with unexpected status code: 201
    14:14:53,749 |-ERROR in biz.paluch.logging.gelf.logback.GelfLogbackAppender[GELF] - Could not send GELF message

I would happily help out and work on a PR, but would like to know which solution you prefer:

a) generally allow 201
b) make this configurable

Cheers

**Comment by mp911de** [comment]
Closed via 2e99088.
