### ISSUE TITLE
Deadlock in logback udp appender

### ISSUE THREAD

**Issue by GEverding** [mp911de/logstash-gelf#117]
Hi, I'm experiencing a weird deadlock in the connect method of GelfUDPSender. I included my logback config and the thread dump of the deadlock. It causes my entire application to completely hault and not process any requests.  

Logstash Gelf Version: 1.11.1
Logback Version: 1.2.2
Deadlock log: https://gist.github.com/GEverding/5736a7a07e94720cbda830e563da86f7
logback.xml: https://gist.github.com/GEverding/b058feebd23a74c90cd8148d113dffb6
Make sure that:

- [ ] You have read the [contribution guidelines](https://github.com/mp911de/logstash-gelf/blob/master/.github/CONTRIBUTING.md).
- [ ] You specify the logstash-gelf version and environment so it's obvious which version is affected
- [ ] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

**Comment by mp911de** [comment]
Thanks for filing the ticket. At the first sight, it looks like a deeply nested circular lock during the connect sequence. The first thread trying to append `GelfLogbackAppender` runs into a lock. Logback raises a lock to synchronize appender addition and the next thread runs into the logback lock.

I don't have a clue yet why `AbstractInterruptibleChannel.blockedOn` happens and locks up the system. It _looks_ like `HystrixTimer-2` gets hold of some internal locks of the `DatagramChannel` and interferes with `GelfLogbackAppender`.

Which Java version (including build number `java -version`) are you running?

**Comment by GEverding** [comment]
Sorry, I really don't like github issues/notifications. 

```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by mp911de** [comment]
Thanks a lot. The stack looks like a self-made deadlock. The thread `HystrixTimer-2` attempts to interrupt Thread `hystrix-sh.weme.wemesh.conductor.commands.mesh-7` in which the UDP connect is in progress. `commands.mesh-7` seems to finish with its initialization and then tries to acquire a lock which is held by `HystrixTimer-2`.

It looks like a synchronization bug inside the JRE implementation. You might want to post the stack trace of both threads to http://bugreport.java.com/.

**Comment by mp911de** [comment]
Seems we can't make any further progress on this ticket, hence closing it.
