### ISSUE TITLE
logstash-server can not receive message

### ISSUE THREAD

**Issue by wlyu** [mp911de/logstash-gelf#122]
hello!
from  log4j   to  logstash 5.6.3 , logstash-server can not receive message, 
but I  use logstash 2.3.4  , logstash-server can  receive message ok!
I don`t know what happend.
Centos 7.0

**Comment by mp911de** [comment]
Which version of logstash-gelf do you use? Could you also post your config for the `GelfLogAppender`?

**Comment by wlyu** [comment]
3ks , and  this is the config
##########################1
      <dependency>
            <groupId>biz.paluch.logging</groupId>
            <artifactId>logstash-gelf</artifactId>
            <version>1.11.1</version>
        </dependency>
##########################1
#log4j.appender.gelf=biz.paluch.logging.gelf.log4j.GelfLogAppender
#log4j.appender.gelf.Threshold=ERROR
#log4j.appender.gelf.Host=tcp:192.168.56.102
#log4j.appender.gelf.originHost=192.168.56.1
#log4j.appender.gelf.Port=6666
#log4j.appender.gelf.Version=1.0
#log4j.appender.gelf.Facility=java-test
#log4j.appender.gelf.ExtractStackTrace=true
#log4j.appender.gelf.FilterStackTrace=true
#log4j.appender.gelf.MdcProfiling=true
#log4j.appender.gelf.TimestampPattern=yyyy-MM-dd HH:mm:ss,SSSS
#log4j.appender.gelf.MaximumMessageSize=8192
#log4j.appender.gelf.AdditionalFields=self_name=my_sdk2,fieldName2=fieldValue2
#log4j.appender.gelf.AdditionalFieldTypes=self_name=String,fieldName2=Double,fieldName3=Long
#log4j.appender.gelf.MdcFields=mdcField1,mdcField2
#log4j.appender.gelf.DynamicMdcFields=mdc.*,(mdc|MDC)fields
#log4j.appender.gelf.IncludeFullMdc=true
### flume ###

**Comment by mp911de** [comment]
Thanks a lot. Logstash requires an UDP connection. Setting `log4j.appender.gelf.Host=tcp:192.168.56.102` will use TCP.
