### ISSUE TITLE
Udp round robin can support it?

### ISSUE THREAD

**Issue by mrdear** [mp911de/logstash-gelf#127]
I have more than one graylog server node, client load balancing in udp mode can use hosts?

example

10.1.1.2 some.net
10.1.1.3 some.net
10.1.1.4 some.net

Then GelfLogbackAppender send each time you choose a different ip.

If not, then you can support this approach?

**Comment by mp911de** [comment]
Hi, that's not supported and won't be supported. Please handle this cases via a load balancer.
