### ISSUE TITLE
How to include marker field

### ISSUE THREAD

**Issue by Verdoso** [mp911de/logstash-gelf#136]
Hi there,

I'm trying to get the appender to send the marker as a field and I can't seem to find how to configure it. 

I have read the documentation at http://logging.paluch.biz/default-fields.html about the default fields but I don't see them in logstash. All I'm doing right now is 
`stdout` { codec => rubydebug }
so I'm not stripping any field. 

I've also tried adding it as a Field using the pattern layout syntax:

`<Field` name="marker" literal="%marker" />

And all I get is 
> Mar 28 14:23:34 slogsweb logstash[23353]: "@timestamp" => 2018-03-28T12:23:33.871Z,
Mar 28 14:23:34 slogsweb logstash[23353]: "marker" => "%marker"

I'm using log4j2 and my config looks like:
```
    <Gelf name="gelf"
          host="tcp:x.y.w.z"
          port="12201"
          version="1.0"
          extractStackTrace="true"
          filterStackTrace="true"
          mdcProfiling="true"
          includeFullMdc="true"
          maximumMessageSize="8192"
          originHost="%host"
          ignoreExceptions="true"
    >
      <Field name="timestamp" pattern="%d{dd MMM yyyy HH:mm:ss,SSS}" />
      <Field name="level" pattern="%level" />
      <Field name="simpleClassName" pattern="%C{1}" />
      <Field name="className" pattern="%C" />
      <Field name="server.fqdn" pattern="%host{fqdn}" />
      <Field name="application" literal="${applicationName}" /><!-- this one comes from a property -->
      <Field name="marker" literal="%marker" />
    </Gelf>
```
Note: I can see the marker being printed if I use a patterny layout
`<PatternLayout` pattern="%-5p|%d{ISO8601}{GMT}|%marker|%c{1}|%m%ex%n" />

Am I missing something?
Thanks

**Comment by mp911de** [comment]
Have you tried `<Field name="marker" pattern="%marker" />`?

**Comment by Verdoso** [comment]
Yeah, if you check the config I included, it's the last field. But all I get is '%marker', as if it was a constant.

**Comment by Verdoso** [comment]
Forget it. I see now literal vs pattern.
I will try.
Thanks

**Comment by Verdoso** [comment]
Simply confirm that that was the issue.
Thanks
