### ISSUE TITLE
Feature Request: StaticField lazy initialization on runtime by code.

### ISSUE THREAD

**Issue by adorechen** [mp911de/logstash-gelf#137]
thanks a lot for supplying the GELF Appender for graylog and logstash. these days, I use it send logs to graylog for spark application. but all the logs from different spark application mixed together, it makes me confused when debugging some exceptions. 

can you let user lazy initialized the literal value (eg. applicationId) at runtime by user's code.

thank you in advance.

[environment]
compile 'biz.paluch.logging:logstash-gelf:1.11.2'

[configuration]
< Field name="applicationId" literal="lazy initial spark application id" />

**Comment by adorechen** [comment]
<Field name="applicationId" literal="lazy initial spark application id" />

**Comment by adorechen** [comment]
<Field name="applicationId" literal="lazy initial spark application id" />

**Comment by mp911de** [comment]
That has to go either into MDC or your logging configuration. Log4j2 and other frameworks support evaluation of variables (System variables, environment variables) that are evaluated during runtime. 

You can override the actual system property value at a later stage.

See https://logging.apache.org/log4j/2.0/manual/lookups.html for further reference.

**Comment by adorechen** [comment]
get it, thanks very much.
