### ISSUE TITLE
How configure RegexReplacement  in GelfLogbackAppender?

### ISSUE THREAD

**Issue by sleski** [mp911de/logstash-gelf#139]
Hi, in Logback I am able to configure RegexReplacement, and do not log some sensitive data. It is possible to configure something similar in GelfLogbackAppender?

My current config looks like below:

```
<appender` name="gelf" class="biz.paluch.logging.gelf.logback.GelfLogbackAppender">
                <host>ssl:${graylog_host}</host>
                <port>12201</port>
                <version>1.1</version>
                <facility>gelf</facility>
                <extractStackTrace>true</extractStackTrace>
                <filterStackTrace>true</filterStackTrace>
                <mdcProfiling>true</mdcProfiling>
                <mdcFields>securityId,requestId,internalToken</mdcFields>
                <timestampPattern>yyyy-MM-dd HH:mm:ss,SSSS</timestampPattern>
                <maximumMessageSize>8192</maximumMessageSize>
                <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
                    <level>INFO</level>
                </filter>
            </appender>
```

I can not find any information about this in documentation.

**Comment by mp911de** [comment]
logstash-gelf has no feature to filter/post-process data that is contained in log events. The only thing that could be possible is implementing a custom filter (such as `ch.qos.logback.classic.filter.ThresholdFilter`) to suppress the actual log event.

**Comment by sleski** [comment]
Hi, thanks for very fast answer. Could you give me a hint, how can I do it? I am new in this logger stuff :-)

**Comment by mp911de** [comment]
Take a look at the Logback dev guide or the code (https://github.com/qos-ch/logback/blob/master/logback-examples/src/main/java/chapters/filters/SampleFilter.java).

**Comment by SlawomirLeski** [comment]
Hi, I would like to mask instead of suppress. So Is it possible to use PatternLayout with Gelf?
Regards.

**Comment by mp911de** [comment]
Sorry, that's not possible.

**Comment by SlawomirLeski** [comment]
TurboFilter should also work?
