### ISSUE TITLE
Switch off additional fields while using Logback

### ISSUE THREAD

**Issue by burningalchemist** [mp911de/logstash-gelf#144]
Hi!

Could you please advise how I can switch off all the additional fields while using logback, like these:

> SourceClassName
> SourceSimpleClassName
> SourceMethodName
> SourceLineNumber

Currently, when `default-logstash-fields.properties` doesn't exist I observe all the additional fields. So far I would like to keep only default fields (as in the documentation) like:

> host
> short_message
> full_message
> timestamp (Java millis/1000)
> level (syslog severity)
> facility

I have found a workaround, when I provide `default-logstash-fields.properties` with the content like:
`""=Time`, then I see only default values in my logging solution. Still, it looks ugly and I think there should be a better way.

Kind regards,
Sergei

**Comment by mp911de** [comment]
`default-logstash-fields.properties` allows customization of fields but it does not allow switching off all fields. It must contain at least one field.

Care to elaborate why you want to disable all auxiliary fields? That's typically a task for logstash filters.

**Comment by burningalchemist** [comment]
Got it, thank you!

Generally, to keep the log output more uniform with the other applications without additional adjustments on Logstash side. They are also described in the documentation as additional fields, so my expectation was that by default I only send default fields.

Currently, my team is using log4j2 for apps, and recently another app was developed, which is using logback. So the idea was to achieve the same message layout without adding new fields and touching filters.

**Comment by mp911de** [comment]
This library wasn't really developed for this use but rather to submit as much data as possible.
However, feel free to fork this library and tailor it to your needs.

I'd keep this ticket open to see how common this use case is and wait for votes.

**Comment by manasvigupta** [comment]
Hello,

First, I wanted to thank you for creating this useful library.

Coming to this issue - I think few attributes should be optional & turned off by default. These are listed below and they have common characteristic - **performance impact while logging using log4j**.  Essentially, all these attributes that are related to caller location logging.

SourceClassName
SourceSimpleClassName
SourceMethodName
SourceLineNumber

There is performance cost while logging this info since log4j creates new Throwable() for each log statement & parses it.

I have blogged more about this issue here -> https://medium.com/@manasvi/do-not-enable-caller-location-logging-with-log4j-3c90f9aaabdb

Either,
1) these attributes should be optional and turned off by default, or,
2) there should be a way to turn off these attributes.

Let me know your thoughts.

Thanks
Manasvi

**Comment by manasvigupta** [comment]
Also, my suggestion is to prefer option # 1 (from previous comment) i.e. turn off caller location attributes by default.

Just for comparison - log4j2, which support gelf layout also does not log caller location attributes by default (i don't think it provides any option to enable it also).

**Comment by mp911de** [comment]
Thanks a lot. Thinking in the way of including/excluding caller location details is a reasonable approach that does not touch filtering of fields. Adding this configuration switch is an easy exercise as we need to add configuration flags to the appender/formatters we're providing.

Location details would stay included by default to not break the current behavior. Users that want to disable location details could set e.g. `IncludeLocation=false`.

**Comment by manasvigupta** [comment]
Ok that works too. Thanks!

**Comment by manasvigupta** [comment]
I am going to take stab at this today.  I haven't looked at code yet, but, I am hoping its a small change.

**Comment by manasvigupta** [comment]
Ok, so, I have fix ready & tested with Log4J.  

I will raise a pull request for your review by this weekend or early next week.

**Comment by mp911de** [comment]
That's in place now.

**Comment by manasvigupta** [comment]
Nice.  :+1: 

You beat me to it. 

How long does it for 1.12.0 version (with these changes) to reflect in maven repository?

**Comment by mp911de** [comment]
@manasvigupta Can you file a new bug report?
