### ISSUE TITLE
GelfLayout for log4j2 1.2 does not expose includeLocation property

### ISSUE THREAD

**Issue by manasvigupta** [mp911de/logstash-gelf#149]
Hi,

I am seeing this warning when i use "includeLocation" attribute as param with log4j 1.2

**log4j:WARN No such property [includeLocation] in biz.paluch.logging.gelf.log4j.GelfLayout.**

It seems that setter for "includeLocation" is missing in **GelfLayout.java**.

Log4j.xml configuration

       <layout class="biz.paluch.logging.gelf.log4j.GelfLayout">
           <param name="ExtractStackTrace" value="true" />
           <param name="IncludeLocation" value="false" />
           <param name="MdcFields" value="X-Correlation-Id" />
       </layout>

pom.xml dependencies - 

	<dependency>
	    <groupId>biz.paluch.logging</groupId>
	    <artifactId>logstash-gelf</artifactId>
	    <version>1.12.0</version>
	</dependency>
    <dependency>
      <groupId>log4j</groupId>
      <artifactId>log4j</artifactId>
      <version>1.2.16</version>
    </dependency>

Thanks
Manasvi

**Comment by mp911de** [comment]
Thanks, that's fixed now.

**Comment by manasvigupta** [comment]
Hi,

Thanks for fixing this issue.

Would it be possible to release this fix as non-snapshot (as it seems to have been merged in snapshot version)?

Thanks
Manasvi

**Comment by mp911de** [comment]
Yes, it will be released. There's no date scheduled for 1.12.1. Feel free to build your own version and deploy it to your artifact repository, if you run one until a release is available.
