### ISSUE TITLE
logstash-gelf on tomcat common loader classpath leads to conflicts with applications using log4j2

### ISSUE THREAD

**Issue by nlighten** [mp911de/logstash-gelf#153]
I am using logstash-gelf 1.11.2 in combination with Tomcat 8.5.33 to send Tomcat server logs to graylog.  Example config:

`
biz.paluch.logging.gelf.jul.GelfLogHandler.host=udp:${log.host}
biz.paluch.logging.gelf.jul.GelfLogHandler.port=12201
biz.paluch.logging.gelf.jul.GelfLogHandler.version=1.1
biz.paluch.logging.gelf.jul.GelfLogHandler.facility=${log.facility}
biz.paluch.logging.gelf.jul.GelfLogHandler.additionalFields=${log.additionalFields}
biz.paluch.logging.gelf.jul.GelfLogHandler.extractStackTrace=true
biz.paluch.logging.gelf.jul.GelfLogHandler.filterStackTrace=true
biz.paluch.logging.gelf.jul.GelfLogHandler.timestampPattern=yyyy-MM-dd HH:mm:ss,SSSS
biz.paluch.logging.gelf.jul.GelfLogHandler.maximumMessageSize=8192
`

To achieve this I have placed logstash-gelf jar in $CATALINA_BASE/lib directory. This works fine in combination with most applications. 

Recently we deployed a Tomcat application from an external vendor that uses log4j2.  Tomcat fails to startup with the following error:

`
27-Aug-2018 08:15:17.282 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Error configuring application listener of class [info.magnolia.init.MagnoliaServletContextListener]
 java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/appender/AbstractAppender
	at java.lang.ClassLoader.defineClass1(Native Method)
`

I suspect that somehow log4j2 uses the wrong classloader when trying to load the log4j2 classes. I found the following options to resolve this issue:

1. Add logstash-gelf jar to application war file. This resolves the issue but is typically difficult to do for applications provided by external vendors (luckily Tomcat has some options to override the webapp classloader).
2. Remove the Log4j2Plugins.dat from the logstash-jar. 

The fact that removing Log4jPlugin.dat resolves the issue may indicate that when log4j2 finds this file (which is on Tomcat's common loader) it subsequently also tries to load all log4j2 classes through the same classloader, even if the applications itself does not have a logstash-gelf log4j2 appender configured. Not sure if this a log4j2 issue or intended behavior.

I am looking for a clean solution for this problem and would appreciate you thoughts on this. One option could be to create separate jars for the different integrations that logstash-gelf offers (or at least separate out log4j2) as this would allow to select only Java Util Logging for my specific use case.

**Comment by mp911de** [comment]
Thanks for reporting this issue.

The following happens here:

1. Applications that use Log4j2 scan the entire classpath for `Log4jPlugin.dat` files.
2. Found `Log4jPlugin.dat` files are inspected for plugins.
3. Plugins are loaded, one of these is `GelfLogAppender`. 
4. Loading of the `GelfLogAppender` class fails as there is no Log4j2 library on the classpath.

Being more specific, the applications' Log4j2 library tries to load `GelfLogAppender` as it has access to all parent classloaders. `GelfLogAppender` is loaded by the [common classloader](https://tomcat.apache.org/tomcat-8.0-doc/class-loader-howto.html) that has `$CATALINA_BASE/lib` under control but has no access to the application classloader. Therefore, class loading fails as the common classloader sees no Log4j2 library.

I think you could do another thing here (besides patching `logstash-gelf`). You could drop the WebApp's Log4j jar files into `$CATALINA_BASE/lib`.

Logstash Gelf is kept simple by intent bundling integrations into a single Jar file. The issue sounds more like a generic Log4j2 issue than a Logstash-Gelf one as Log4j2 should rather back off if it cannot load a plugin - at least the [code in the plugin component](https://github.com/apache/logging-log4j2/blob/e741549928b2acbcb2d11ad285aa84ee88728e49/log4j-core/src/main/java/org/apache/logging/log4j/core/config/plugins/util/PluginRegistry.java#L185) indicates this intent.

**Comment by nlighten** [comment]
Thank you for your swift analysis. I was confused why there was no logstash-gelf related class was in the stacktrace. I increased the log level of the WebappClassLoaderBase and can now see that it delegates the loading to the parent classloader for GelfLogAppender which can find it but not the depended log4j2 classes (hence the NoClassDefFoundError and not a ClassNotFoundException:

I understand that you are not eager to split the codebase in multiple jars. I think that for now I will opt for patching the jar during the creation of our Tomcat docker base image. I will also raise an issue for log4j2 project to ask them to consider also handing unchecked exceptions while loading plugins.

Thanks again.

**Comment by nlighten** [comment]
For completeness sake: issue should be fixed in  log4j-core-2.11.2 once released.

See [LOG4J2-2422](https://issues.apache.org/jira/browse/LOG4J2-2422)
