### ISSUE TITLE
Tomcat hangs if Graylog is unable to handle GELF messages?

### ISSUE THREAD

**Issue by royrwood** [mp911de/logstash-gelf#157]
I just encountered an odd problem using logstash-gelf with Tomcat and JDK logging.  The root cause was that the Graylog instance that I'm sending to ran out of disk space and was unable to process incoming messages.  Interestingly, Tomcat completely hung very quickly after restarting and trying to push GELF messages to Graylog.

This was with logstash 1.11.2, so not the latest version, I know.  Java version is 1.8.0_144.  Tomcat is 8.5.23.  System OS is Mac OSX 10.11.6.

Is this expected behaviour for gelfstash?  Has the behaviour changed in later revisions of gelfstash?  Or perhaps this is a Tomcat issue?

The relevant sections from my logging.properties file are:

handlers = org.apache.juli.FileHandler, biz.paluch.logging.gelf.jul.GelfLogHandler
.handlers = org.apache.juli.FileHandler, biz.paluch.logging.gelf.jul.GelfLogHandler

.level=INFO

biz.paluch.logging.gelf.jul.GelfLogHandler.host=tcp:10.0.20.110
biz.paluch.logging.gelf.jul.GelfLogHandler.port=12201
biz.paluch.logging.gelf.jul.GelfLogHandler.version=1.1
biz.paluch.logging.gelf.jul.GelfLogHandler.facility=java-test
biz.paluch.logging.gelf.jul.GelfLogHandler.extractStackTrace=true
biz.paluch.logging.gelf.jul.GelfLogHandler.filterStackTrace=true
biz.paluch.logging.gelf.jul.GelfLogHandler.timestampPattern=yyyy-MM-dd HH:mm:ss,SSSS
biz.paluch.logging.gelf.jul.GelfLogHandler.maximumMessageSize=8192

**Comment by mp911de** [comment]
Can you attach also a thread dump to see where the process is blocked?

**Comment by royrwood** [comment]
I'll try and get the thread dump ASAP.  Things are crazy busy today, so it will take some time to get that.

And thanks for the quick reply!

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
