### ISSUE TITLE
GELF Message is invalid

### ISSUE THREAD

**Issue by WayneSchlegel** [mp911de/logstash-gelf#158]
I keep getting error 
`GELF`` Message is invalid: {"host":"<my server name>,"timestamp":"1539162937.998","level":"6","facility":"logstash-gelf","_LoggerName":"hybrisserver","_SourceSimpleClassName":"AbstractTenant","_SourceClassName":"de.hybris.platform.core.AbstractTenant","_Time":"2018-10-10 11:15:37,0998","_Severity":"INFO","_SourceLineNumber":475,"_Thread":"localhost-startStop-5","_SourceMethodName":"logInitializationInfo"}`
in my hybris server environment (tomcat based).

Configuration is as follows:
```
    log4j2.appenders = console, graylog
    log4j2.rootLogger.appenderRef.graylog.ref=graylog
    log4j2.appender.graylog=biz.paluch.logging.gelf.log4j2.GelfLogAppender
    log4j2.appender.graylog.type=GELF
    log4j2.appender.graylog.name=graylog
    log4j2.appender.graylog.host=tcp:<my server name>
    log4j2.appender.graylog.port=12201
```

When I add the following configuration lines:
```
    log4j2.appender.graylog.tags.type=Field
    log4j2.appender.graylog.tags.name=tags
    log4j2.appender.graylog.tags.literal=TestApplicationID
```
I receive the following error:
`GELF Message is invalid: {"host":"<my server name>","timestamp":"1539164230.492","level":"6","facility":"logstash-gelf","_tags":"TestApplicationID"}`

It looks like many fields get lost. How can I get essential gelf fields like version?

Environment: 
logstash-gelf 1.12.0, hybris commerce suite 1808, Java 1.8.0_181-b13 64 Bit on Windows 10

console.log:
https://gist.github.com/WayneSchlegel/ef03a636bf0c4de9bc35abb61cfc6f42

**Comment by mp911de** [comment]
Thanks for the report and sorry for the long radio silence, I missed this ticket. The reason for reporting an invalid message is that the log event does not contain a message. Looking at the JSON from the attached gist, there's no `message`/`short_message` field.

Please filter such messages from your GELF appender.
