### ISSUE TITLE
Cleanup pooled buffers on log handler/appender disposal

### ISSUE THREAD

**Issue by dgolobor** [mp911de/logstash-gelf#159]
I use logstash-gelf with a Grails application, that is deployed to tomcat.

When stopping a tomcat service, tomcat reports an error in catalina.out:

_SCHWERWIEGEND: The web application [/xxx] created a ThreadLocal with key of type [biz.paluch.logging.gelf.intern.PoolHolder$ThreadLocalPoolHolder$1] (value [biz.paluch.logging.gelf.intern.PoolHolder$ThreadLocalPoolHolder$1@2550747]) and a value of type [biz.paluch.logging.gelf.intern.ReusableGzipOutputStream] (value [biz.paluch.logging.gelf.intern.ReusableGzipOutputStream@283891a7]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak._

There is no other problems except this message.

My environment:
logstash-gelf 1.12.0, Oracle Linux 7.5, Tomcat  7.0.76.0, Grails 3.3.8, Java 1.8.0_171-b10

**Comment by mp911de** [comment]
When you stop Tomcat, it's likely that you also exit your JVM which then cleans up all pooled buffers. Not cleaning up resources becomes an issue for rolling application deployments.

We should introduce `ThreadLocal` clean up for Log handlers/appenders that support resource cleanup.

**Comment by mp911de** [comment]
It looks there isn't really anything we can do about. `ThreadLocal`s cannot be cleared for all threads. Resources are (re)used from various threads and we would need to disassociate each thread. Since we do not have access to threads or thread-locals, we cannot perform a cleanup.
