### ISSUE TITLE
Sending JBoss 6.4 managed_server_ip and managed_server_name values to graylog-beta 2.4.6

### ISSUE THREAD

**Issue by hasantahsinakin** [mp911de/logstash-gelf#160]
Can we send managed_server_ip and managed_server_name values to graylog with "additionalFields" like below?

```
<custom-handler name="GelfLogger" class="biz.paluch.logging.gelf.jboss7.JBoss7GelfLogHandler" module="biz.paluch.logging">
    <level name="INFO" />
    <properties>
        <property name="additionalFields" value="managed_server_ip=fieldValue1,managed_server_name=fieldValue2" />
        <property name="additionalFieldTypes" value="managed_server_ip=String,managed_server_name=String" />
    </properties>
</custom-handler>
```

**Comment by mp911de** [comment]
What is `managed_server_ip`? If it's a static field, then the configuration from above will work.

**Comment by hasantahsinakin** [comment]
Actually i got managed_server_ip and managed_server_name properties from another gelf jar module, which i use for one of the two graylog servers i send logs. One module cannot send logs to two graylog servers. 

I think the static fields, you ask are "server name" and "group" below, am i right?

`<servers> 

    <server name="ServerOne" group="ServerGroup"/>

    <server name="ServerTwo" group="ServerGroup"/>

</servers>`

**Comment by mp911de** [comment]
Sounds as if you're mixing up things here. Features that are applicable for other GELF libraries are not necessarily applicable for Logstash GELF.

Coming back to your question: 

> Can we send managed_server_ip and managed_server_name values to graylog with "additionalFields" like below?

Looking at the config above, this seems reasonable.

I'm going to close this issue as the question is answered. If you face other issues, feel free to create another issue.

**Comment by hasantahsinakin** [comment]
I see. Thank you.
