### ISSUE TITLE
How to remove message field?

### ISSUE THREAD

**Issue by emregozen** [mp911de/logstash-gelf#163]
Hi,

I am using 1.12.0 version with Log4j2 2.11.1,
When using old version(org.graylog2.log4j2:log4j2-gelf), there was just one message field,
But now there are two,
   - message(short)
   - full_message(full)

So, is there any way to remove message field, I want to see just full_message and keep payload simple and small,

Thanks in advance.

**Comment by mp911de** [comment]
No, there’s no possibility to suppress either one. Please note that short_message is a required field as per the GELF spec. full_message is optional per Spec but we’re sending it to retain the non-truncated message.

http://docs.graylog.org/en/2.4/pages/gelf.html
Am 14. Nov. 2018, 12:23 +0000 schrieb emregozen <notifications@github.com>:
