### ISSUE TITLE
Feature request: turn off error if GELF server is not available on startup

### ISSUE THREAD

**Issue by lbroman** [mp911de/logstash-gelf#164]
I'm using LogbackGelfAppender v. 1.12.0

When using the LogbackGelfAppender in a spring-boot application, the appender initialization will throw an error during application start and the spring-boot application will exit if the configured host cannot be resolved.

The error presented is
```
2018-11-20 20:28:34.848 ERROR 19507 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in biz.paluch.logging.gelf.logback.GelfLogbackAppender[AUDIT] - Unknown GELF server hostname:udp:audit-logstash java.net.UnknownHostException: audit-logstash: Name or service unknown
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)

```

My feature request is to add a configuration option to the appender configuration which would let the appender initialize without causing this error. This could result in an error message and perhaps a later attempt at resolving and connecting.

**Comment by mp911de** [comment]
Sorry, this won't happen. Raising initialization errors upon startup is essential to make sure an application started up properly. There is no later in that case and appenders do not refresh/retry in the background.
