### ISSUE TITLE
ERROR Appenders contains an invalid element or attribute "Gelf"

### ISSUE THREAD

**Issue by shadyb** [mp911de/logstash-gelf#167]
Logstash-gelf: 1.1.0
Logger:            log4j2 (via spring boot)
JDK:                 10
Dep Manager: Gradle

Error messages:
```
2018-11-29 08:09:18,177 main ERROR Appenders contains an invalid element or attribute "Gelf"
2018-11-29 08:09:18,218 main ERROR Unable to locate appender "gelf" for logger config "root"
2018-11-29 08:09:19,287 main ERROR Appenders contains an invalid element or attribute "Gelf"
2018-11-29 08:09:19,290 main ERROR Unable to locate appender "gelf" for logger config "root"
```
Config:
https://gist.github.com/shadyb/741c7f8e6464ceaf58644f2df45bf1ac

Gradle dep:
```
compile     ('biz.paluch.logging:logstash-gelf:1.1.0') {
    exclude group: 'ch.qos.logback'  // causes conflicts with log4j2
}
```
Not sure why this isn't working. I noticed the packages specified in the Configuration tag (biz.paluch.logging.gelf.log4j2) in the log4j2 example is invalid; there is no log4j2 class in the logstash-gelf jar, only a log4j class. If I use that class, I still get the same error message.

Please advise.

**Comment by mp911de** [comment]
1.1.0 is an ancient version that is not maintained since 5 years. Please upgrade to 1.12.0 which is the [most recent](https://github.com/mp911de/logstash-gelf/releases/tag/logstash-gelf-1.12.0) release.

**Comment by shadyb** [comment]
Thanks for pointing that out. That's what happens when you work 13 hours straight :\.
