### ISSUE TITLE
log4j-slf4j-impl don't work on docker, graylog server can not receive message

### ISSUE THREAD

**Issue by dotyso** [mp911de/logstash-gelf#168]
Log4j2 is working normally on docker
Logger logger = LogManager.getLogger(getClass().getName());

Slf4j don't work on docker, graylog server can not receive message
Logger logger = LoggerFactory.getLogger(getClass().getName());

**Comment by mp911de** [comment]
Nothing I can do about. This is a Java library and I cannot solve infrastructure issues with non-JVM technologies.
