### ISSUE TITLE
off-heap memory so large

### ISSUE THREAD

**Issue by codetomylaw** [mp911de/logstash-gelf#169]
I use ：      

```
<Gelf name="gelf" host="udp:xxxx" port="12201" version="1.1" extractStackTrace="true"
              facility="center_server" filterStackTrace="true" mdcProfiling="true" includeFullMdc="true"
              maximumMessageSize="8192" originHost="%host{fqdn}"
              additionalFieldTypes="fieldName1=String,fieldName2=Double,fieldName3=Long">
            <Field name="timestamp" pattern="%d{dd MMM yyyy HH:mm:ss,SSS}" />
            <Field name="level" pattern="%level" />
            <Field name="simpleClassName" pattern="%C{1}" />
            <Field name="className" pattern="%C" />
            <Field name="server" pattern="%host" />
            <Field name="server.fqdn" pattern="%host{fqdn}" />
        </Gelf>
```
 My  project   JVM   :
-Xms2g -Xmx2g -Xmn1g -Xss1024K -XX:MetaspaceSize=128M -XX:MaxMetaspaceSize=512M

About  4g  used  from  off-heap memory ，  it  is  so crazy 。

I get  something  from   native  memory  dump file：

INFOclassNamcom..impl.SSI"04 Dec 2018 11:50:36,"}%W{"host":"13-62","short_message":"xxxx"
"facility":"xxxx_server","_server.fqdn":"13-62","_server":"13-62","_level":"INFO","_className":"com.xxx.cheatguard.tool.TongChengCheckTool","_simpleClaF%%UHnb?ECE4 vt1}&U}=k`ol","_timestamp":"04 Dec 2018 11:50:36,349

because use  netty ？ the   message   for  off-heap memory ？

**Comment by mp911de** [comment]
logstash-gelf uses an object pool for memory and objects to reduce GC pressure by reusing pooled object instances. You can disable pooling by setting the following system properties:

```
logstash-gelf.message.pooling=false
logstash-gelf.buffer.size=0
```

The result is that no pooling is used and buffers required for sending GELF messages will be garbage collected.

**Comment by codetomylaw** [comment]
@mp911de how to  use  for   log4j2 ?

**Comment by mp911de** [comment]
You need to set system properties on startup (e.g. `java -Dlogstash-gelf.message.pooling=false -Dlogstash-gelf.buffer.size=0 …`)

**Comment by codetomylaw** [comment]
> You need to set system properties on startup (e.g. `java -Dlogstash-gelf.message.pooling=false -Dlogstash-gelf.buffer.size=0 …`)

I  see， thanks！

**Comment by codetomylaw** [comment]
> logstash-gelf uses an object pool for memory and objects to reduce GC pressure by reusing pooled object instances. You can disable pooling by setting the following system properties:
> 
> ```
> logstash-gelf.message.pooling=false
> logstash-gelf.buffer.size=0
> ```
> The result is that no pooling is used and buffers required for sending GELF messages will be garbage collected.

What causes this problem？please show  some code for me。 
about  15 applications  use  PoolingGelfMessage， find  only  one  application  use off-heap more then 5g。 I can't find why ？

**Comment by mp911de** [comment]
I have two pointers:

`ThreadLocal` buffer allocation: https://github.com/mp911de/logstash-gelf/blob/master/src/main/java/biz/paluch/logging/gelf/intern/sender/GelfTCPSender.java#L34

Decision whether to use pooled buffers: https://github.com/mp911de/logstash-gelf/blob/master/src/main/java/biz/paluch/logging/gelf/intern/sender/GelfTCPSender.java#L107

We have similar pooling in `GelfUDPSender`.

**Comment by fred01** [comment]
> > logstash-gelf uses an object pool for memory and objects to reduce GC pressure by reusing pooled object instances. You can disable pooling by setting the following system properties:
> > ```
> > logstash-gelf.message.pooling=false
> > logstash-gelf.buffer.size=0
> > ```
> > The result is that no pooling is used and buffers required for sending GELF messages will be garbage collected.
> 
> What causes this problem？please show some code for me。
> about 15 applications use PoolingGelfMessage， find only one application use off-heap more then 5g。 I can't find why ？

It's highly depends on your log message size.

**Comment by codetomylaw** [comment]
> > > logstash-gelf uses an object pool for memory and objects to reduce GC pressure by reusing pooled object instances. You can disable pooling by setting the following system properties:
> > > ```
> > > logstash-gelf.message.pooling=false
> > > logstash-gelf.buffer.size=0
> > > ```
> > > The result is that no pooling is used and buffers required for sending GELF messages will be garbage collected.
> > 
> > 
> > What causes this problem？please show some code for me。
> > about 15 applications use PoolingGelfMessage， find only one application use off-heap more then 5g。 I can't find why ？
> 
> It's highly depends on your log message size.

no ,  because I user pooling message.  it is a bug.
logstash-gelf   reuse  buffer for each thread  by  ThreadLocal  ,   but  if  your application  thread is not  reuse , the off-heap memory  will   so large.
