### ISSUE TITLE
Double initialization of SSLSession in GelfTCPSSLSender

### ISSUE THREAD

**Issue by DbImko** [mp911de/logstash-gelf#181]
Hi,

I think we have a problem in method connect() of GelfTCPSSLSender class

https://github.com/mp911de/logstash-gelf/blob/7553c8e196a55a84b760bc37ef736e11c706b6f9/src/main/java/biz/paluch/logging/gelf/intern/sender/GelfTCPSSLSender.java#L55-L65

As you can see, you initialize `sslEngine` and `sslSession` fields right away, after `connect` method is done, we will have channel with `sslEngine`.
In multithreaded environment if two threads will call `sendMessage` method at the same time, one will initialise channel and `sslSession`, and second will recreate `sslEngine` and `sslSession`. 

This leads us to situation like `javax.net.ssl.SSLException: Received fatal alert: ...` on client side,
and `javax.crypto.BadPaddingException: ciphertext sanity check failed` on server side

Make sure that:

- [X] You have read the [contribution guidelines](https://github.com/mp911de/logstash-gelf/blob/master/.github/CONTRIBUTING.md).
- [X] You specify the logstash-gelf version and environment so it's obvious which version is affected
- [X] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

**Comment by mp911de** [comment]
Thanks for reporting an issue.

> In multithreaded environment if two threads will call sendMessage method at the same time, one will 

The call to `connect()` in `sendMessage(…)` is guarded with a lock, so there must be a loop hole somewhere. It would also make sense to move initialization into the `if(super.connect(…))` block, but that's an optimization.

https://github.com/mp911de/logstash-gelf/blob/a8d749e2bb77f0aea94db62164734a21fd4adfbd/src/main/java/biz/paluch/logging/gelf/intern/sender/GelfTCPSender.java#L100-L105

I'm not exactly sure, I'd suspect rather concurrent access to `SSLEngine` and `SSLSession` changing their state without proper synchronization.

**Comment by DbImko** [comment]
loop hole in overridden connect call in GelfTCPSSLSender, it recreates `sslEngine` and `sslSession`.
you should check whether connection is established or not inside overridden `connect` method, and accept my PR.
Or move initialization of `sslEngine` and `sslSession` under `if(super.connect(…))`, as you proposed.

Any way both solutions work, you should choose which one to use =)

**Comment by mp911de** [comment]
Thanks for the hint. It makes sense now. The double checked lock isn't properly implemented for SSL because two threads can sequentially access `connect()` and the second call to `isConnected()` happens in `GelfTCPSender`. A second caller recreates the SSL resources and that's the bug.

Do you want to adjust your PR to move the initialization of `sslEngine` and `sslSession` under `if(super.connect(…))`?

**Comment by DbImko** [comment]
I don't understand your point, but moved initialization under if(super.connect(...)).

I just want to make it clear.
Two threads want to send a message.
1. They call `sendMessage()` method on object which is `GelfTCPSSLSender` instance. 
`GelfTCPSSLSender` class doesn't have method `sendMessage()`, so call goes to method `sendMessage()` in `GelfTCPSender` class of object which is GelfTCPSSLSender instance. 
2. in method `sendMessage()` has check whether it is connected or not. (in our case it's not)
3. then happens synchronization for method `connect()`
4. in `connect()` method of `GelfTCPSSLSender` object we are trying to test connection one more time.
It happens under synchronization, and if connection was established, no double initialization of `sslEngine` field wouldn't happen.

**Comment by mp911de** [comment]
That's fixed via #182 now. Thanks a lot.

**Comment by DbImko** [comment]
Okay, thank you.
