### ISSUE TITLE
No log is sent to Graylog

### ISSUE THREAD

**Issue by phuongtailtranminh** [mp911de/logstash-gelf#187]
## Logs

[logback-spring.xml](https://gist.github.com/phuongtailtranminh/88acc84becebef9ebe8dd799e0c7d32b)

[pom.xml](https://gist.github.com/phuongtailtranminh/8d18db9fae5c3381557a20ed38d4f576)

GrayLog docker instance

![image](https://user-images.githubusercontent.com/12473996/54346596-f2331f80-4677-11e9-9752-3f2054bfce0a.png)

The application run normally but there is no log be sent to Graylog server

**Comment by phuongtailtranminh** [comment]
Just notice that I have to create Input in order to receive the message

In GrayLog management site (http://localhost:9000) => System -> Inputs -> GELF TCP -> Launch New Input

The Bingo! Your log shown up

**Comment by njohnson-una** [comment]
I'm glad I ran across this.  Perhaps Mark should add a troubleshooting page to https://logging.paluch.biz that shows this information.  @mp911de what do you think?
