### ISSUE TITLE
Gelf appender slows down application start.

### ISSUE THREAD

**Issue by TheRealHypo** [mp911de/logstash-gelf#188]
## Log File:
https://gist.github.com/TheRealHypo/f52a1c1964c2c02e03bfc01c732b55a3

## Config:
https://gist.github.com/TheRealHypo/757cd1e49ec34c2ff37473c58031bb96

## Versions:
Gradle: 4.10.3
Log4j2: 2.11.2
logstash-gelf: 1.12.0

## Issue:
- When starting the application with GELF Appender active, the startup time increases by 20s

## Reproduce:
- Start application with attached log4j2.xml configuration.
- Log4j2 Log says it takes 20s in createAppenders() for Graylog appender

## Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/mp911de/logstash-gelf/blob/master/.github/CONTRIBUTING.md).
- [x] You specify the logstash-gelf version and environment so it's obvious which version is affected
- [x] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

**Comment by mp911de** [comment]
This is likely due to hostname lookup. Please disable hostname lookup (see [documentation for further reference](https://logging.paluch.biz/hostname-lookup.html)) and retry.

**Comment by mp911de** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by TheRealHypo** [comment]
Hey, sorry for the late reply, I have been on vacation. 

I just disabled hostname lookup through VM parameter -Dlogstash-gelf.skipHostnameResolution=true and it seems to work way faster now. 

Is it possible to set this variable In a static {} block at the beginning of the application ? Or is it too late then already ?

**Comment by mp911de** [comment]
This depends on who/how your logging configuration gets initialized. If you have your logging/application bootstrapping fully under control (before any process touches logstash-gelf), then you should be able to reliably set the system property in your code. 

In any other case (application server, some component boots your JAR, …), you might get away setting the property _before_ any log events are shipped to logstash. No guarantee this will work.

Alternatively, you can also use environment variables  (`$ export "logstash-gelf.skipHostnameResolution"=true`), if you can't get hold of system properties on JVM start.

**Comment by TheRealHypo** [comment]
I already noticed that the question was kinda dumb 😅
Since I deploy the app via FxLauncher as Native installer, the FxLauncher handles VM parameter. Works like a charm now. Thanks for the help. 😊
