### ISSUE TITLE
Implement integration test for Thorntail

### ISSUE THREAD

**Issue by cchet** [mp911de/logstash-gelf#193]
Therefore that this library now provides a Thorntail specific module.xml along with a thorntail specific documentation, I think this library should also test its integration with thorntail.

https://docs.thorntail.io/2.2.0.Final/#testing-in-a-container_thorntail
 
The implementation of the test should be similar to the existing wildfly integration tests.

**Comment by mp911de** [comment]
Thanks for this ticket. I'm not convinced to spend more time on Thorntail. We have quite dated WildFly tests and I assume we would need to upgrade an entire stack of dependencies to make things work on Thorntail.

**Comment by cchet** [comment]
You could introduce a new project for defining a minimal thorntail service which implements the test as well. Of course the new project needs at least java 8 to be running and these tests would be outside the main project, which I wouldn't consider a bad approach. It wouldn't be allowed to be a child of the main project or we need a profile for java 8+. 

The main project itself doesn't need to be modified at all as far as I assume, it just need do be present in the local repo on thorntail repackaging to a standalone service.

**Comment by mp911de** [comment]
This is all effort I'm not keen on doing so. Sure, this sounds fun in the first moment but it comes with a long list of things to do. Feel free to create your own repo with a logstash-gelf Thorntail integration test and a TravisCI build setup of which you take care of. This isn't a candidate for the main logstash-gelf project.
