### ISSUE TITLE
Basic authentication to graylog server

### ISSUE THREAD

**Issue by chka73** [mp911de/logstash-gelf#194]
Version 1.13.0

Documentation request/ feature request.

Looking for information about if I can configure the Gelf appender to use basic authentication to our Graylog server?

**Comment by mp911de** [comment]
Have you tried adding credentials to the HTTP url (`http://user:pass@server`)?

**Comment by chka73** [comment]
Yes. Tried that as first choice. Getting a 401 response from server though so my guess was that the user part of the URL was stripped in some step?

**Comment by mp911de** [comment]
We had once a ticket #150 to add basic auth, but we never followed up on that one. So currently, there is no basic authentication support.

**Comment by cchet** [comment]
@mp911de 
I would like to implement that

**Comment by mp911de** [comment]
Feel free to give it a spin. Make sure to stay Java 6-compatible.

**Comment by arvidvillen** [comment]
Any updates on this?

**Comment by mp911de** [comment]
Pull requests are welcome!

**Comment by arvidvillen** [comment]
Hi,
Is java 6 still a requirement?
Do you think `DatatypeConverter` could be used for base64 encoding?

**Comment by mp911de** [comment]
That one comes from the JAXB package. Currently, the baseline is Java 1.7. It’s fine if we ship our own Base64 implementation as package-private utility. Ideally, we an find a source that is as well under MIT license to not violate any license terms.

**Comment by arvidvillen** [comment]
Do you think we could use this one?
https://github.com/chdh/base64coder-java/blob/master/src/main/java/biz/source_code/base64Coder/Base64Coder.java

**Comment by mp911de** [comment]
The referenced code should be fine. Feel free to come up with a PR. We should keep the Base64 support package-private and make sure to include the full license header to preserve its origin.
