### ISSUE TITLE
Reconnect interval to support load balancing?

### ISSUE THREAD

**Issue by jbye** [mp911de/logstash-gelf#201]
Thank you for your work on this library.

This is perhaps more a question than an issue. Is there support for establishing a new connection at a set interval for load balancing purposes (TCP)?

**Comment by mp911de** [comment]
No. Logstash-gelf communicates with a single endpoint only. Typically, that would be your load balancer.

**Comment by jbye** [comment]
I understand, thank you for the reply. Just to give you some background as to why I was asking. 

We have configured logstash-gelf to point at a load balancer, but because the connection is long-lived logstash-gelf will keep talking to the same instance behind the load balancer. Had it reconnected every 5 minutes or so (we use logstash-gelf across many different services), it would over time spread the load more evenly.

**Comment by mp911de** [comment]
How about using HTTP as transport? HTTP has somewhat more overhead but if you're looking more after spreading load than this could be a viable option.

**Comment by jbye** [comment]
Thank you for the suggestion. We'll definitely consider HTTP while exploring our options :)
