### ISSUE TITLE
Is it possible to have pattern layout messages working?

### ISSUE THREAD

**Issue by cristianb1989** [mp911de/logstash-gelf#202]
Could you please provide an example on how to create  a log message containing the Timestamp, ThreadId, ClassName:
log4j.appender.graylog2.layout.ConversionPattern=%d{yy-MM-dd HH:mm:ss} [%t] %-5p %c{2}: %m%n

 Basically I'd like to have the possibility creating pattern layouts like here:
https://logging.apache.org/log4j/2.x/manual/layouts.html#PatternLayout

Is this a functionality supported? Please bear in mind that it was working here https://github.com/graylog-labs/log4j2-gelf

**Comment by mp911de** [comment]
Just to make sure, we're talking about Log4j2. 

You can use log4j2 substitutions in your logging config. See [`log4j2-dynamic-mdc.xm`](https://github.com/mp911de/logstash-gelf/blob/master/src/test/resources/log4j2/log4j2-dynamic-mdc.xml) for an example.
