### ISSUE TITLE
Changing system properties does not change their value in the logs

### ISSUE THREAD

**Issue by gaspardpetit** [mp911de/logstash-gelf#203]
When calling `System.setProperty`, one would expect that references to the system property in a literal (ex. `literal="${sys:my_property}"`) would also change. However this is not the case, it appears that the gelf appender caches the initial value when the appender is created, making it impossible to update the field at runtime.

The following unit test, to be added in [GelfLogAppenderSystemPropertiesTests.java](https://github.com/mp911de/logstash-gelf/blob/master/src/test/java/biz/paluch/logging/gelf/log4j/GelfLogAppenderSystemPropertiesTests.java) outlines the issue:

```
@Test
void testChangeProperties() throws Exception {

    System.setProperty(PROPERTY1, PROPERTY1_VALUE);

    setup();
    Logger logger = loggerContext.getLogger(getClass().getName());

    logger.info(LOG_MESSAGE);
    assertThat(GelfTestSender.getMessages()).hasSize(1);

    GelfMessage gelfMessage0 = GelfTestSender.getMessages().get(0);

    assertThat(gelfMessage0.getField("propertyField2")).isEqualTo(PROPERTY1_VALUE);
    
    System.setProperty(PROPERTY1, PROPERTY2_VALUE);

    logger.info(LOG_MESSAGE);
    assertThat(GelfTestSender.getMessages()).hasSize(2);

    GelfMessage gelfMessage1 = GelfTestSender.getMessages().get(1);

    assertThat(gelfMessage1.getField("propertyField2")).isEqualTo(PROPERTY2_VALUE);
}
```

This test results in the following output:

```
Failed tests:
  GelfLogAppenderSystemPropertiesTests.testChangeProperties:116
Expecting:
 <"value of myproperty">
to be equal to:
 <"value of otherproperty">
but was not.
```

Before submitting a pull request I would like to make sure this is considered a bug and not the expected behaviour. Note that a regular console appender in log4j2 does update `sys:my_property` values when the system properties are updated at runtime.

**Comment by gaspardpetit** [comment]
Running 

```
LoggerContext context = (LoggerContext) LogManager.getContext(false);
context.reconfigure();
```

appears to be a workaround for now

**Comment by mp911de** [comment]
This is how Log4j behaves, `GelfLogAppender` isn't doing anything special to resolve system properties. Log4j processes the xml/properties-config, resolves system properties at the time the config is loaded and provides resolved values to `GelfLogAppender`.
