### ISSUE TITLE
GelfHTTPSender calls getBytes() without a charset

### ISSUE THREAD

**Issue by liufitch** [mp911de/logstash-gelf#207]
- logstash-gelf version :1.13.0

- logback version:1.0.13

 **configuration:**

```
  <appender name="GELF" class="biz.paluch.logging.gelf.logback.GelfLogbackAppender">
        <host>https://**************/gelf</host>
        <version>1.1</version>
        <facility>logstash-gelf</facility>
        <additionalFields>***********</additionalFields>
        <additionalFieldTypes>*************</additionalFieldTypes>
        <maximumMessageSize>8192</maximumMessageSize>
    </appender>
```
The graylog support charset utf-8.  but it shows incorrect chinese, so i want to set charset UTF-8 in the _GelfLogbackAppender_ .but  i didnt find any like charset tags.

Thanks.

**Comment by mp911de** [comment]
Can you grab a hex-dump of a packet and one of how it should be to investigate the issue?

There's no charset option that could be set.

We're using our own UTF-8 encoding, see https://github.com/mp911de/logstash-gelf/blob/master/src/main/java/biz/paluch/logging/gelf/intern/JsonWriter.java#L209.

**Comment by liufitch** [comment]
thanks for your answer. i find the problem.  its a environment problem.
if `getBytes()` has no any params, it will use system default encode.
reference:
[https://docs.azure.cn/zh-cn/articles/azure-operations-guide/app-service-web/aog-app-service-web-java-qa-solve-messy-code-during-sending-chinese-characters-to-third-party-services](url)

**Comment by mp911de** [comment]
Is that a `getBytes` call in logstash-gelf? If so, can you share a link to see whether we can do something about it?

**Comment by liufitch** [comment]
yeah.  i just add a configuration file called web.config in the  _site/wwwroot_  folder and the content is 
```
<configuration>
  <system.webServer>
    <handlers>
      <add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="%AZURE_TOMCAT85_HOME%\bin\startup.bat" arguments="">
      <environmentVariables>
        <environmentVariable name="JAVA_OPTS" value="-Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8" />
      </environmentVariables>
    </httpPlatform>
  </system.webServer>
</configuration>
```.

**Comment by mp911de** [comment]
That isn't what I asked for. Where is the call to `getBytes()`?

**Comment by liufitch** [comment]
- package:  biz.paluch.logging.gelf.intern.sender

- method:  boolean sendMessage(GelfMessage message)
`  HttpURLConnection connection = null;

        boolean var5;
        try {
            connection = (HttpURLConnection)this.url.openConnection();
            connection.setConnectTimeout(this.connectTimeoutMs);
            connection.setReadTimeout(this.readTimeoutMs);
            connection.setDoOutput(true);
            connection.setRequestMethod("POST");
            connection.addRequestProperty("Content-type", "application/json");
            OutputStream outputStream = connection.getOutputStream();
            outputStream.write(message.toJson().getBytes());
            outputStream.close();
            int responseCode = connection.getResponseCode();
            if (responseCode < 200 || responseCode > 299) {
                this.errorReporter.reportError("Server responded with unexpected status code: " + responseCode, (Exception)null);
                return false;
            }

            var5 = true;
        } catch (IOException var9) {
            this.errorReporter.reportError("Cannot send data to " + this.url, var9);
            return false;
        } finally {
            if (connection != null) {
                connection.disconnect();
            }

        }

        return var5;
    }`

**Comment by mp911de** [comment]
Thanks a lot. We're working with UTF8 all the time so we should change `message.toJson().getBytes()` to use UTF8 there as well.

**Comment by mp911de** [comment]
That's fixed now.
