### ISSUE TITLE
Q: Distinction between what's out in the wild

### ISSUE THREAD

**Issue by xasx** [mp911de/logstash-gelf#209]
Hey Mark,

maybe it's worth distinguishing out the purpose of this software, especially differentiate against:
* encoders only
* handlers only

What do you think? I see colleagues being a bit confused about what it does and when to use what. E.g. consider the STDOUT/fluentd case where no sending is needed at all.

Thanks and regards
:wave: A.

**Comment by mp911de** [comment]
Thanks for report. I'm happy to include a bit of documentation. Care to submit a PR?

**Comment by mp911de** [comment]
Closing this one as this ticket goes nowhere without any activity.
