### ISSUE TITLE
Question regarding ThreadLocal vars

### ISSUE THREAD

**Issue by sfuhrm** [mp911de/logstash-gelf#221]
Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/mp911de/logstash-gelf/blob/master/.github/CONTRIBUTING.md).
- [x] You specify the logstash-gelf version and environment so it's obvious which version is affected
- [x] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

 

This question affects the current source (1.14.0-SNAPSHOT).

There are many places where a `ThreadLocal` variable is used:

```
src/main/java/biz/paluch/logging/gelf/GelfMessageAssembler.java:    private final ThreadLocal<PoolingGelfMessageBuilder> builders;
src/main/java/biz/paluch/logging/gelf/GelfMessageAssembler.java:            builders = new ThreadLocal<PoolingGelfMessageBuilder>() {
src/main/java/biz/paluch/logging/gelf/intern/PoolHolder.java:        private final ThreadLocal<ReusableGzipOutputStream> streamPool = new ThreadLocal<ReusableGzipOutputStream>() {
src/main/java/biz/paluch/logging/gelf/intern/PoolHolder.java:        private final ThreadLocal<ByteBuffer[]> singleBufferPool = new ThreadLocal<ByteBuffer[]>() {
src/main/java/biz/paluch/logging/gelf/intern/PoolHolder.java:        private final ThreadLocal<byte[]> byteArrayPool = new ThreadLocal<byte[]>() {
src/main/java/biz/paluch/logging/gelf/intern/OutputAccessor.java:        private final ThreadLocal<ByteBufferOutputAccessor> accessorPool = new ThreadLocal<ByteBufferOutputAccessor>() {
src/main/java/biz/paluch/logging/gelf/intern/OutputAccessor.java:        private final ThreadLocal<ByteBufferOutputStream> streamPool = new ThreadLocal<ByteBufferOutputStream>() {
src/main/java/biz/paluch/logging/gelf/intern/sender/GelfTCPSender.java:    private final ThreadLocal<ByteBuffer> writeBuffers = new ThreadLocal<ByteBuffer>() {
src/main/java/biz/paluch/logging/gelf/intern/sender/GelfBuffers.java:    protected static ByteBuffer[] toUDPBuffers(GelfMessage message, ThreadLocal<ByteBuffer> writeBuffers,
src/main/java/biz/paluch/logging/gelf/intern/sender/GelfBuffers.java:            ThreadLocal<ByteBuffer> tempBuffers) {
src/main/java/biz/paluch/logging/gelf/intern/sender/GelfBuffers.java:    protected static ByteBuffer toTCPBuffer(GelfMessage message, ThreadLocal<ByteBuffer> writeBuffers) {
src/main/java/biz/paluch/logging/gelf/intern/sender/GelfBuffers.java:    private static void enlargeBuffer(ThreadLocal<ByteBuffer> buffers) {
src/main/java/biz/paluch/logging/gelf/intern/sender/GelfBuffers.java:    private static ByteBuffer getBuffer(ThreadLocal<ByteBuffer> buffers) {
src/main/java/biz/paluch/logging/gelf/intern/sender/AbstractNioSender.java:    private final ThreadLocal<ByteBuffer> readBuffers = new ThreadLocal<ByteBuffer>() {
src/main/java/biz/paluch/logging/gelf/intern/sender/GelfTCPSSLSender.java:    private final ThreadLocal<ByteBuffer> sslNetworkBuffers = new ThreadLocal<>();
src/main/java/biz/paluch/logging/gelf/intern/sender/GelfTCPSSLSender.java:    private final ThreadLocal<ByteBuffer> tempBuffers = new ThreadLocal<>();
src/main/java/biz/paluch/logging/gelf/intern/sender/GelfUDPSender.java:    private final ThreadLocal<ByteBuffer> writeBuffers = new ThreadLocal<ByteBuffer>() {
src/main/java/biz/paluch/logging/gelf/intern/sender/GelfUDPSender.java:    private final ThreadLocal<ByteBuffer> tempBuffers = new ThreadLocal<ByteBuffer>() {
```

A `ThreadLocal` variable will keep all instances of all threads until the holding thread dies. For a long-running server, there could be thousands of threads polluting the `ThreadLocal` variables and eating up valuable direct ByteBuffers. SonarLint has an [issue](https://rules.sonarsource.com/java/RSPEC-5164) for that proposing to call `ThreadLocal.remove()` whenever a Thread has finished working with an object. I think that many places don't have such a clear lifecycle.

**Example:** `GelfUDPSender` will be in memory from the initialization of the loggers until the end of each thread.

**Example code:** I have added example code that shows that each thread keeps its thread local until thread death when you're debugging the test case. See https://gist.github.com/sfuhrm/ab459d877d0073b6be6ed565c9ff770d 
The showcase throws `java.lang.OutOfMemoryError: Direct buffer memory`

**Question:** Does it make sense to replace the per-thread singletons with dynamic instances to not run into heap problems? Another option would be using [object pools](https://commons.apache.org/proper/commons-pool/).

**See also:** https://www.baeldung.com/java-memory-leaks#7-using-threadlocals

**Comment by mp911de** [comment]
These `ThreadLocal`'s are thread-local buffer pools for memory. The alternative would be a proper memory pool (such as Netty's pooled `ByteBuf`). We decided on a simple approach to keep the library small while enabling low-latency scenarios and reducing the GC pressure. If we would come up with our own buffer pooling, then likely this library would turn into a memory pool implementation instead of helping with GELF sending.

> For a long-running server, there could be thousands of threads polluting the ThreadLocal variables and eating up valuable direct ByteBuffers

True. The library is intended to be used with pooled threads (such as WildFly, Tomcat, Netty) and not for applications that create and dispose millions of threads.

**Comment by mp911de** [comment]
Related: @sfuhrm do you like to get more involved in this project? I've seen you help across various tickets and this library had its genesis in a 1&1 project.

**Comment by sfuhrm** [comment]
@mp911de regarding involvement: let's see whether I'll have enough time in the next weeks + re-discuss. The library is used in many projects at work at 1&1 and it simply works what I really like :-).

**Comment by sfuhrm** [comment]
Regarding the general question: I guess the problem only arises with ca. 6000 _active_ threads. That's not very likely and it doesn't pay off to write a object pool. 

@mp911de thanks for clarification.
