### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by karolbmx** [mp911de/logstash-gelf#223]
Hi,
I'm using Apache Camel and i want to send to graylog additional field taken from CamelContext (i.e. http headers ).How to add new field to gelf in java?
Currently I'm using GELF UDP with this configuration:

log4j.appender.gelf=biz.paluch.logging.gelf.log4j.GelfLogAppender
log4j.appender.gelf.Threshold=INFO
log4j.appender.gelf.Host=udp:x.x.x.x
log4j.appender.gelf.Port=x
log4j.appender.gelf.Version=1.1
log4j.appender.gelf.Facility=java-test
log4j.appender.gelf.ExtractStackTrace=true
log4j.appender.gelf.FilterStackTrace=true
log4j.appender.gelf.MdcProfiling=true
log4j.appender.gelf.TimestampPattern=yyyy-MM-dd HH:mm:ss,SSSS
log4j.appender.gelf.MaximumMessageSize=8192
Thanks

**Comment by mp911de** [comment]
You have two options:

* If `CamelContext` is `ThreadLocal`, then you can extend the logging appender with its own event type and iterate over the context (see https://github.com/mp911de/logstash-gelf/blob/master/src/main/java/biz/paluch/logging/gelf/log4j/Log4jLogEvent.java)
* Alternatively, copy the values from `CamelContext` into the `MDC`.
