### ISSUE TITLE
biz.paluch.logging.gelf.log4j.GelfLogAppender kills whole system if remote server unavailable

### ISSUE THREAD

**Issue by ckuiawa** [mp911de/logstash-gelf#237]
Using the biz.paluch.logging.gelf.log4j.GelfLogAppender, when the graylog server is not available, an exception occurs that stops the whole process.  
The best way I could reproduce this is to get a working log up and running and change the port.  On start, a SocketTimeoutException is thrown, which kills the whole application.

```
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]: log4j:ERROR Cannot send data to https://<graylogserver>:20001/gelf
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]: java.net.SocketTimeoutException: connect timed out
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at java.net.PlainSocketImpl.socketConnect(Native Method)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at java.net.Socket.connect(Socket.java:589)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at biz.paluch.logging.gelf.intern.sender.GelfHTTPSender.sendMessage(GelfHTTPSender.java:61)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at biz.paluch.logging.gelf.log4j.GelfLogAppender.append(GelfLogAppender.java:97)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at org.apache.log4j.Category.callAppenders(Category.java:206)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at org.apache.log4j.Category.forcedLog(Category.java:391)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at org.apache.log4j.Category.log(Category.java:856)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at org.slf4j.impl.Log4jLoggerAdapter.info(Log4jLoggerAdapter.java:305)
Mar 10 15:25:26 i-0ba934134c5557da5 connect-standalone.sh[2357]:         at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:68)
```

I found this when pushing my service to prod because I didn't have the correct terraform configuration for my host to talk to graylog.  Instead of the service starting and just not sending to graylog, the exception kills the entire process.  
It seems to me like this has been fixed for the log4j2 appender, which takes an optional parameter to handle exceptions or throw them up the chain.  That seems like a good solution for the 1.x logger.  I would use the 2.x logger, but I have dependencies on stuff that depends on 1.x, so I can't.

Environment:
I am running a Kotlin service using Kafka's connect-standalone to run.

**Comment by mp911de** [comment]
There isn't much we can do about it. Using HTTP implies using the TCP protocol which comes with a connection handshake. Each log event that goes through `GelfLogAppender` and the `GelfHTTPSender` causes a HTTP request. If the remote peer is not available, your application will suffer severely from connect timeouts. While you can configure connect/read timeouts, we rather recommend the use of a load balancer to ensure higher availability. 

Alternatively, use either UDP to drop log events in case Graylog is unavailable or dump log  events to a file (using the JSON formatter) and incrementally load the file into Graylog.

The Log4j2 appender has an option to propagate/swallow any exceptions during log message processing. I/O errors are typically logged to the status/error logger of each logging framework to avoid upstream propagation.

I'm inclined to close this ticket unless there's something we could do here.

**Comment by ckuiawa** [comment]
Why can't you add an option similar to the Log4j2 appender?  I would rather lose some messages to Graylog than lose my service.  

If that's not reasonable, then at the very least, could you make it very clear in the Javadoc that if using http, and any exception happens, that the program will end?

**Comment by mp911de** [comment]
I think there's quite a misconception here. Log4j2 allows explicitly for exception propagation while Log4j's (and also all the other logging frameworks) prohibit upstream exception propagation.

It's not that a single HTTP failure causes your application to stop from working. It's more the fact that each log event issues a HTTP request and this cumulative arrangement causes effectively a lock-up of the application. Each non-UDP appender can easily cause this situation since that's the nature of TCP. 

You could try mitigating the issue by wrapping `GelfLogAppender` in a async appender with a bounded queue.
