### ISSUE TITLE
logstash-gelf calls deprecated and removed LogEvent.getContextData() 

### ISSUE THREAD

**Issue by esakilpi** [mp911de/logstash-gelf#240]
logstash-gelf calls org.apache.logging.log4j.core.LogEvent.getContextData() method that has been deprecated since log4j2 v. 2.7 and later removed. It has been replaced by getContextMap().
This seems to be the reason why no log gets sent.

logstash-gelf v. 1.14.0
log4j2 v. 2.13

**Comment by mp911de** [comment]
Feel free to submit a pull request.

**Comment by esakilpi** [comment]
This only happens when doing mcd profiling. The remedy is to remove all references to mcd from log4j2.xml, including attributes mdcProfiling="true" includeFullMdc="true".

**Comment by mp911de** [comment]
Actually, it's the other way round. `LogEvent.getContextMap` is deprecated since 2.7 while `getContextData()` was introduced in 2.7. Closing this ticket as everything is as it should be.
