### ISSUE TITLE
Auto extraction of json properties into Graylog fields

### ISSUE THREAD

**Issue by HalitTalha** [mp911de/logstash-gelf#241]
Hello there,
Thanks for this great library. This is more like a question or a feature request.
I wonder if logstash-gelf supports auto extraction of a json message into graylog fields for log4j2 or any other framework?

**Comment by mp911de** [comment]
Not sure I follow. Do you mean something like `logger.info("{'my': 'JSON field'}");` to be extracted in to a GELF message field of `{'message': '…', '_my' : 'JSON field'`}`?

**Comment by HalitTalha** [comment]
> Not sure I follow. Do you mean something like `logger.info("{'my': 'JSON field'}");` to be extracted in to a GELF message field of `{'message': '…', '_my' : 'JSON field'`}`?

Exatcly. Sorry for being unclear.

**Comment by mp911de** [comment]
No, there's no such feature and we don't plan to introduce that kind of features as we would be required to parse the log message and this introduces performance and complexity overhead.
