### ISSUE TITLE
Stop method is not called by Log4j2

### ISSUE THREAD

**Issue by zhv** [mp911de/logstash-gelf#243]
Hello,
seems like it is a bug. I noticed that Log4j2 did not call stop() method for GelfAppender. I'm using biz.paluch.logging.gelf.log4j2.GelfLogAppender (logstash-gelf 1.13.0) & log4j 2.11.1, for this combination of versions Gelf appender is a part of hierarchy:
```
class GelfLogAppender extends AbstractAppender
AbstractAppender (org.apache.logging.log4j.core.appender)
    AbstractFilterable (org.apache.logging.log4j.core.filter)
        AbstractLifeCycle (org.apache.logging.log4j.core)
            LifeCycle2 (org.apache.logging.log4j.core)
                LifeCycle (org.apache.logging.log4j.core)
            ...
```
and [Log4j just checks if appender is LifeCycle2](https://github.com/apache/logging-log4j2/blob/log4j-2.11.1-patches/log4j-core/src/main/java/org/apache/logging/log4j/core/config/AbstractConfiguration.java#L341) and call default 2-args AbstractLifeCycle.stop(long, TimeUnit), not a method from GelfLogAppender.

The latest Log4j has slightly different code [AbstractConfiguration.java#L394](https://github.com/apache/logging-log4j2/blob/e7a1d9d93ee9620fb289a37090fc28d0ed12a2f4/log4j-core/src/main/java/org/apache/logging/log4j/core/config/AbstractConfiguration.java#L394) but I think behavior will be the same.

could you please check?

Best regards,
Vyacheslav

**Comment by mp911de** [comment]
`GelfLogAppender` extends `AbstractAppender` which implements `LifeCycle2`. Since `GelfLogAppender` overrides only `stop()` and not `stop(long, TimeUnit, boolean)`, the `GelfSender` was never closed. It makes sense to change the override.
