### ISSUE TITLE
Clarify the documentation for WildFly JSON Formatter

### ISSUE THREAD

**Issue by oers** [mp911de/logstash-gelf#245]
In https://logging.paluch.biz/examples/wildfly-json.html the following ist stated:

extractStackTrace | Send the Stack-Trace to the StackTrace field (true/false) | false
-- | -- | --

It is unclear what the StackTraceField is. The defaults are:

fields | Comma-separated list of log event fields that should be included in the JSON | Time, Severity, ThreadName, SourceClassName, SourceMethodName, SourceSimpleClassName, LoggerName, NDC, Server
-- | -- | --

Should the User add an extra field StackTrace here, or is this some automagic? I can't find a reference to the StackTrace-Field in the documentation anywhere.

Thanks for any feedback.

**Comment by mp911de** [comment]
logstash-gelf extracts LogEvent fields to JSON fields. So enabling `extractStackTrace` will create a JSON field containing the stack trace.
