### ISSUE TITLE
No Sysout and Syserr from Wildfly 20 sent to Graylog 

### ISSUE THREAD

**Issue by lhug** [mp911de/logstash-gelf#253]
Hi,
I am connecting my dockerized wildfly server to my dockerized graylog container via udp. A lot of messages already come through with this, but it seems that tehre are several messages that are not being sent, and I cannot seem to find out why.

First and Second, sysout and syserr messages are apparently not picked up. This is a problem, as a lot of the libraries used just fire their stacktraces into syserr and are done then. The FILE- and CONSOLE-Loggers receive the messages, though.

Third, It seems like certain loggers are also not sent, specifically `org.jboss.modules.define` and `io.undertow.request`.
Again, FILE and CONSOLE do log them, so I guess they are being processed by the root logger.

---
Graylog container uses graylog 3.3, exposes port 12201/UPD to host machine
Wildfly container, which is in another network, uses wildfly 20.0.1.FINAL
also using gelf logging module with dependencies logstash-gelf-1.12.0, jedis-2.9.0, commons-pool2-2.4.3, I am unsure which version of yourlogger this applies to.

the logger is configured like so:
```
<custom-handler name="GELF" class="biz.paluch.logging.gelf.wildfly.WildFlyGelfLogHandler" module="biz.paluch.logging">
  <level name="DEBUG"/>
  <properties>
    <property name="host" value="udp:host.docker.internal"/>
    <property name="version" value="1.1"/>
    <property name="extractStackTrace" value="true"/>
    <property name="filterStackTrace" value="true"/>
    <property name="mdcProfiling" value="true"/>
    <property name="includeFullMdc" value="true"/>
  </properties>
</custom-handler>
```
the logging.properties file is updated and modified as defined in standalone.xml, so "configuration not picked up" should not be the case here

**Comment by mp911de** [comment]
I cannot help you with Wildfly. You might want to ask this question in the Wildfly forums.
