### ISSUE TITLE
Q: Log4j2 default fields together with additional fields

### ISSUE THREAD

**Issue by CarlKarlssonSchmidt** [mp911de/logstash-gelf#257]
Hi! We are upgrading Log4j to Log4j2 and ran in to troubles with the combination of additional default fields (The additional fields listed here: https://logging.paluch.biz/default-fields.html) and static fields. In log4j2/GelfLogAppender combining the DefaultMapping-fields and static fields are blocked. Is there another way of combining the two? In Log4j this was not a problem.

Best regards,

Carl

Make sure that:

- [ ] You have read the [contribution guidelines](https://github.com/mp911de/logstash-gelf/blob/master/.github/CONTRIBUTING.md).
- [ ] You specify the logstash-gelf version and environment so it's obvious which version is affected
- [ ] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

**Comment by mp911de** [comment]
In general, leaving `<Fields/>` unconfigured will default to include the following fields:

`Time, Severity, ThreadName, SourceClassName, SourceMethodName, SourceLineNumber, SourceSimpleClassName, LoggerName, Marker`.

As soon as you configure at least one field, the defaulting backs off and you have full control over all fields (except for these which are mandated by the Gelf spec). Does that help?

**Comment by CarlKarlssonSchmidt** [comment]
Thanks for the quick reply! It was the connection between PatternLogMessageField and LogMessageField that was the missing link! For anyone out there who stumbles upon this, we solved it by:

    appender.gelf.Severity.type = Field
    appender.gelf.Severity.name = Severity
    appender.gelf.Severity.pattern = %level{length=5}

with the pattern definitions found here: http://logging.apache.org/log4j/2.x/manual/layouts.html#PatternLayout

**Comment by jsmucr** [comment]
> As soon as you configure at least one field, the defaulting backs off and you have full control over all fields (except for these which are mandated by the Gelf spec). Does that help?

@mp911de Has it been always like this? Because currently I'm installing a new version of a software where I was about to configure GELF logging, and suddenly the default fields (such as `LoggerName`) disappeared and only the ones I added myself stayed.
Old software version worked with 1.11.1 and Log4j 1.2, the new one I'm trying to make work with 1.15.0 and Lg4j2.

**Comment by mp911de** [comment]
Log4j v1 used a fixed (predefined) fieldset while Log4j v2 provides means to configure each field individually. If you do not configure any `<Field>`s, then you will get a default fieldset. With the first `<Field>` configured, logstash-gelf backs off from its defaults.

**Comment by jsmucr** [comment]
Can I get these default fields back somehow? This old stupid me built some infrastructure on it. 😄

**Comment by mp911de** [comment]
If you remove all `<Field>`s, then you will see the default fields.

**Comment by jsmucr** [comment]
Figured it out:

    <Gelf name="Gelf" version="1.1"
          host="tcp:logging?deliveryAttempts=0&amp;keepAlive=true"
          port="12201"
          extractStackTrace="true"
          filterStackTrace="true"
          includeFullMdc="true">
      <Field name="application" literal="rvs" />
      <Field name="sourceEnvironment" literal="test" />
      <Field name="timestamp" pattern="%d{dd MMM yyyy HH:mm:ss,SSS}" />
      <Field name="level" pattern="%level" />
      
      <Field name="LoggerName" pattern="%logger" />
      <Field name="Severity" pattern="%level" />
      <Field name="Thread" pattern="%tn" />
    </Gelf>
