### ISSUE TITLE
GELF message seems to be missing mandatory field "version"

### ISSUE THREAD

**Issue by mikknormak** [mp911de/logstash-gelf#259]
GELF message format:
https://docs.graylog.org/en/latest/pages/gelf.html
defines:
> version string (UTF-8)
> GELF spec version – “1.1”; MUST be set by client library.

https://github.com/mp911de/logstash-gelf/blob/main/src/main/java/biz/paluch/logging/gelf/intern/GelfMessage.java
des use
> GELF_VERSION_1_1.equals(version)

to define version specific "timestamp" and "level" formats, but does not seem to include a "version" field into final JSON message.
(and since all custom field are prefixed with "_" there is also no (easy) way to manually provide "version" field)

perhaps something like this:
>    public static final String FIELD_VERSION = "version";
> ...
>            if (GELF_VERSION_1_1.equals(version)) {
>                hasFields = writeIfNotEmpty(out, hasFields, FIELD_VERSION, GELF_VERSION_1_1);
>            }

or perhaps more future-proof:
>    public static final String FIELD_VERSION = "version";
> ...
>            if (!isEmpty(version) && !GELF_VERSION_1_0.equals(version)) {
>                hasFields = writeIfNotEmpty(out, hasFields, FIELD_VERSION, version);
>            }

in case GELF_VERSION_1_0 must not include the "version" field

**Comment by mp911de** [comment]
Good catch. I think the second variant makes sense. Do you want to submit a pull request?

**Comment by mikknormak** [comment]
Sure:
https://github.com/mp911de/logstash-gelf/pull/260
