### ISSUE TITLE
Spring Boot log4j2 initialization time

### ISSUE THREAD

**Issue by gordor4** [mp911de/logstash-gelf#262]
Hello! I'm using log4j2 with xml config 
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
    <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
            <PatternLayout
                    pattern="%style{%d{ISO8601}}{black} %highlight{%-5level }[%style{%t}{bright,blue}] %style{%C{1.}}{bright,yellow}: %msg%n%throwable"/>
        </Console>
        <Gelf name="gelf" host="tcp:xx.xx.xx.xx" port="12201" version="1.1" extractStackTrace="true"
              filterStackTrace="true" maximumMessageSize="8192"
              originHost="%host{fqdn}">
            <Field name="timestamp" pattern="%d{dd MMM yyyy HH:mm:ss,SSS}"/>
            <Field name="level" pattern="%level"/>
            <Field name="simpleClassName" pattern="%C{1}"/>
            <Field name="className" pattern="%C"/>
            <Field name="server" pattern="%host"/>
            <Field name="server.fqdn" pattern="%host{fqdn}"/>
        </Gelf>
    </Appenders>

    <Loggers>
        <Root level="info">
            <AppenderRef ref="gelf"/>
            <AppenderRef ref="Console"/>
        </Root>
    </Loggers>
</Configuration>
```
Application without gelf logging starting about 2 seconds, but with additional gelf appender more that 40 sec. Is this is normal start time or I can boost it?

**Comment by gordor4** [comment]
OK, looks like this is OSX problem. Application in docker starting fast

**Comment by gordor4** [comment]
![image](https://user-images.githubusercontent.com/19503560/107786524-11a0be80-6d5f-11eb-94e1-74656b7b9f2e.png)

**Comment by gordor4** [comment]
if anyone face this problem too. Slows down getCanonicalHost name with IPv6 addresses. This is Java spoofing security process. For local development you can use JVM param -Djava.net.preferIPv4Stack=true

**Comment by jklap** [comment]
If you are running JDK 8 less than u113 there was a known JDK bug that also caused slow lookups. Adding an entry to /etc/hosts for your hostname and 127.0.0.1 fixes that issue

**Comment by mp911de** [comment]
The observed delay is very likely caused by the DNS reverse lookup. Check out https://logging.paluch.biz/hostname-lookup.html for options to provide the hostname through the environment.

**Comment by gordor4** [comment]
> The observed delay is very likely caused by the DNS reverse lookup. Check out https://logging.paluch.biz/hostname-lookup.html for options to provide the hostname through the environment.

Thanks
