### ISSUE TITLE
log4j2 kafka appender unable to handle multiple bootstrap hosts, i.e kafka://host1:9092,host2:9092#topic

### ISSUE THREAD

**Issue by cumafo** [mp911de/logstash-gelf#263]
logstash-gelf-1.14.1 on macOS 10.15.7

log4j2-gelf-with-kafka.xml 
...
<Gelf name="gelf" host="kafka://localhost:9092,gotkaftest01:9092#kafka-log-topic" ....
...

## 1.
mvn surefire:test -Dtest=GelfLogAppenderKafkaIntegrationTests

[INFO] Scanning for projects...
[WARNING] The project biz.paluch.logging:logstash-gelf:jar:1.14.1 uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO]
[INFO] ------------------< biz.paluch.logging:logstash-gelf >------------------
[INFO] Building logstash logging connectors 1.14.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M4:test (default-cli) @ logstash-gelf ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running biz.paluch.logging.gelf.log4j2.GelfLogAppenderKafkaIntegrationTests
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 13.006 s <<< FAILURE! - in biz.paluch.logging.gelf.log4j2.GelfLogAppenderKafkaIntegrationTests
[ERROR] biz.paluch.logging.gelf.log4j2.GelfLogAppenderKafkaIntegrationTests.testKafkaSender  Time elapsed: 12.988 s  <<< FAILURE!
org.opentest4j.AssertionFailedError:

Expecting:
 <true>
to be equal to:
 <false>
but was not.
	at biz.paluch.logging.gelf.log4j2.GelfLogAppenderKafkaIntegrationTests.testKafkaSender(GelfLogAppenderKafkaIntegrationTests.java:49)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   GelfLogAppenderKafkaIntegrationTests.testKafkaSender:49
Expecting:
 <true>
to be equal to:
 <false>
but was not.
[INFO]
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.546 s
[INFO] Finished at: 2021-02-16T22:13:13+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-cli) on project logstash-gelf: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/cml/logstash-gelf/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

## 2.
KafkaGelfSenderProvider::getBrokerServers
commenting the "port code" and specifying port on each host in the xml works fine.
....
```javascript
        if (uri.getHost() != null) {
            brokers = uri.getHost();
           /*
            int port;
            if (uri.getPort() > 0) {
                port = uri.getPort();
            } else if (configuration.getPort() > 0) {
                port = configuration.getPort();
            } else {
                port = BROKER_DEFAULT_PORT;
            }
            brokers += ":" + port;
            */
```

test runc mvn surefire:test -Dtest=GelfLogAppenderKafkaIntegrationTests

[INFO] Scanning for projects...
[WARNING] The project biz.paluch.logging:logstash-gelf:jar:1.14.1 uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO]
[INFO] ------------------< biz.paluch.logging:logstash-gelf >------------------
[INFO] Building logstash logging connectors 1.14.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0-M4:test (default-cli) @ logstash-gelf ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running biz.paluch.logging.gelf.log4j2.GelfLogAppenderKafkaIntegrationTests
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.957 s - in biz.paluch.logging.gelf.log4j2.GelfLogAppenderKafkaIntegrationTests
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.676 s
[INFO] Finished at: 2021-02-16T21:56:37+01:00
[INFO] ------------------------------------------------------------------------

**Comment by mp911de** [comment]
Feel free to submit a pull request to fix the issue. Also, there's no need to dump the entire Maven build log. Having a concise description of what you expect and what happens is sufficient.

**Comment by cumafo** [comment]
Hello,
Sorry for the extra noise..
As far as I understand, parsing is done by the non-extendable URI.class which support only one host. The options would then be to find another URI parser for kafka or copy/rewrite the URI code.  Any thoughts?
/C

**Comment by mp911de** [comment]
`URI` can still parse the URL but it returns the details as `authority` and not as `host`.

**Comment by cumafo** [comment]
I'm on my way to do a pull request withe the following changes in KafkaGelfSenderProvider.java:

    private static String getBrokerServers(GelfSenderConfiguration configuration) {

        // extract the host part from uri and put in an array
        // so each host can be validated using the URI
        String kafkaPrefix = KafkaContants.KAFKA_SCHEME + "://";

        String hostsPart = configuration.getHost().substring( kafkaPrefix.length() );
        int tpos = hostsPart.indexOf("#");
        String topic=hostsPart.substring(tpos);
        hostsPart=hostsPart.substring(0, tpos);

        String brokers = "";
        String[] hosts = hostsPart.split(",");
        if (hosts.length>0) for(String host: hosts) {
            String broker;
            String tmp = kafkaPrefix + host + topic;
            URI uri = URI.create(tmp);
            if (uri.getHost() != null) {
                broker = uri.getHost();
                int port;
                if (uri.getPort() > 0) {
                    port = uri.getPort();
                } else if (configuration.getPort() > 0) {
                    port = configuration.getPort();
                } else {
                    port = BROKER_DEFAULT_PORT;
                }
                broker += ":" + port;

            } else {
                broker = uri.getAuthority();
            }
            if (brokers.length()>0)
                brokers += ",";
            brokers += broker;
        }

        if (brokers.isEmpty()) {
            throw new IllegalArgumentException("Kafka URI must specify bootstrap.servers.");
        }

        return brokers;
    }

**Comment by cumafo** [comment]
Now through unit test and made a pull request

**Comment by cumafo** [comment]
Changed the code to read scheme from uri as you requested and it builds and runs locally but not here. Really no idea of whats wrong.
