### ISSUE TITLE
GelfMessageAssembler truncate short_message to 250

### ISSUE THREAD

**Issue by vbo-ks-security** [mp911de/logstash-gelf#270]
I can not find any limitation in Gelf specification regarding the short_message field size.
After we moved from a logback to a log4j2 backend using logstash-gelf's Gelf appender we have issue (due to a custom processing of the field) having this field truncated.

Why hardcoding a maximum size for short_message and not at least let client application definie its own limit if needed?

**Comment by mp911de** [comment]
I'm not quite sure. The limit of 250 stems from the initial commit. It was either related to Logstash or a GELF library that served as a template for logstash-gelf.

**Comment by vbo-ks-security** [comment]
Would you accept a PR making this limit configurable instead of a hard-coded value?

**Comment by mp911de** [comment]
Yes, that will work. We need likely updates to all frontends (log4j, log4j2, JUL, Logback and their layout variants).

**Comment by vbo-ks-security** [comment]
As we need a fix quickly and we will decommission Graylog soon we dediced to use a forked version of the library.
Thank you very much for your time

**Comment by mp911de** [comment]
Thanks for the details. Does this mean I can close this ticket?

**Comment by vbo-ks-security** [comment]
Sure :)
