### ISSUE TITLE
udp fragmentation

### ISSUE THREAD

**Issue by waikup83** [mp911de/logstash-gelf#271]
Make sure that:

- [ ] You have read the [contribution guidelines](https://github.com/mp911de/logstash-gelf/blob/master/.github/CONTRIBUTING.md).
- [ ] You specify the logstash-gelf version and environment so it's obvious which version is affected
- [ ] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

**Comment by mp911de** [comment]
Closing as there's no description of what you're asking for.
