### ISSUE TITLE
Application main thread got blocked with GelfLogbackAppender

### ISSUE THREAD

**Issue by Ravikumar-Ganesan** [mp911de/logstash-gelf#272]
Make sure that:

- [ ] You have read the [contribution guidelines](https://github.com/mp911de/logstash-gelf/blob/master/.github/CONTRIBUTING.md).
- [ ] You specify the logstash-gelf version and environment so it's obvious which version is affected
- [ ] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

 

Hello,

We are using the below appender and the application main thread got blocked. Is there an example which we can include <neverBlock>true</neverBlock> with the Gelf appender? Please help

<Configuration status="INFO">
      <Properties>
            <Property name="environment">*****</Property>
            <Property name="filename">*****</Property>
      </Properties>
      <Appenders>
            
            <Async name="ASYNCGRAYLOG">
                  <AppenderRef ref="graylog" />
            </Async>
            
            <Gelf name="graylog" host="@@GRAYLOG_PROTOCOL@@:@@GRAYLOG_SERVER@@" port="@@GRAYLOG_PORT@@" version="1.1" extractStackTrace="true"
            filterStackTrace="true" mdcProfiling="true" includeFullMdc="true" maximumMessageSize="8192"
            originHost="%host{fqdn}" additionalFieldTypes="application=String,environment=string,application_type=String,application_group=String,layer=String">
                  <Field name="timestamp" pattern="%d{dd MMM yyyy HH:mm:ss,SSS}" />
                  <Field name="level" pattern="%level" />
                  <Field name="simpleClassName" pattern="%C{1}" />
                  <Field name="className" pattern="%C" />
                  <Field name="facility" pattern="esb"/>
                  <Field name="server" pattern="%host" />
                  <Field name="server.fqdn" pattern="%host{fqdn}" />
                  
                  <Field name="application" pattern="@@APP_NAME@@"/>
                  <Field name="environment" pattern="@@ENVIRONMENT@@"/>
                  <Field name="application_group" pattern="@@APPLICATION_GROUP@@" />
                  <Field name="application_type" pattern="esb" />
                  <Field name="envType" literal="@@ENVIRONMENT@@-@@APP_TYPE@@"/>
                  <Field name="layer" pattern="esb" />
                  
                  <Field name="mdcField2" mdc="mdcField2" />
                  <DynamicMdcFields regex="mdc.*" />
                  <DynamicMdcFields regex="(mdc|MDC)fields" />
            </Gelf>
      </Appenders>
      <Loggers>
            <AsyncRoot level="INFO">
                  <AppenderRef ref="ASYNCGRAYLOG" />
            </AsyncRoot>
      </Loggers>
</Configuration>

pom.xml
		<dependency>
			<groupId>biz.paluch.logging</groupId>
			<artifactId>logstash-gelf</artifactId>
			<version>1.11.1</version>
		</dependency>

**Comment by Ravikumar-Ganesan** [comment]
Host is configured with TCP and below is the exception which we got in mule server logs

2021-08-09 10:36:19,227 AsyncAppender-ASYNCGRAYLOG ERROR Connection timed out. Cannot connect to hostname/ip:12201 within 0ms
2021-08-09 10:36:19,227 AsyncAppender-ASYNCGRAYLOG ERROR Could not send GELF message

**Comment by mp911de** [comment]
TCP is a blocking transport and a defunct remote note can block the application entirely. Consider using UDP or an async appender.
