### ISSUE TITLE
Q: Removing "Facility" and "short_message" fields?

### ISSUE THREAD

**Issue by adventl** [mp911de/logstash-gelf#273]
Hello, thank you for this great library.

I am currently using this library together with log4j2, and from the read me I see that if no additional fields are configured, the following fields are automatically included: timestamp, level (syslog level), host, facility, message, short_message. I tried to set the facility field by adding an additional Field tag below

`<Field name="facility" pattern="test"/>`

but it seems to always be "logstash-gelf" on graylog.

I would like to check, is it possible to configure the library to not include "Facility" and "Short Message" in the GelfMessage?

Thank you! 

Make sure that:

- [ ] You have read the [contribution guidelines](https://github.com/mp911de/logstash-gelf/blob/master/.github/CONTRIBUTING.md).
- [ ] You specify the logstash-gelf version and environment so it's obvious which version is affected
- [ ] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

**Comment by mp911de** [comment]
As per Gelf spec, `short_message` is required (a short descriptive message; MUST be set by client library.).

If you do not add any fields, then a set of default fields is added. When you add a `Field`, then your configuration applies. Reporting that this doesn't work is a hint that your configuration isn't correct.

**Comment by adventl** [comment]
Hello mp911de

Thank you for the clarification on short_message, I have also fixed the my configuration xml. Did not notice that "facility" was supposed to be "Facility", I just copied it from the readme.

Thanks!
