### ISSUE TITLE
Return lowercase to first letter of Log Fields

### ISSUE THREAD

**Issue by frankiedrake** [mp911de/logstash-gelf#275]
Is that possible to add some option to make log fields start with a lowercase? I found that in a previous [Gelf-library](https://github.com/graylog-labs/log4j2-gelf) we used it was lowercased
Found this in class `biz.paluch.logging.gelf.LogMessageField`:
```
    public enum NamedLogField {
        Time("Time"), Severity("Severity"), ThreadName("Thread"), SourceClassName("SourceClassName"), SourceSimpleClassName(
                "SourceSimpleClassName"), SourceMethodName("SourceMethodName"), SourceLineNumber("SourceLineNumber"), Server(
                "Server"), LoggerName("LoggerName"), Marker("Marker"), NDC("NDC");
    ...
```

**Comment by mp911de** [comment]
Thanks for reaching out.

The upper case starting letter originates from having these fields visible in reporting tools such as Kibana therefore we never implemented naming strategies or the like. Adding additional configuration to each logger outweighs the demand for such a feature. I recommend forking this library and adjusting the necessary bits in your fork.
