### ISSUE TITLE
exceptionClass, exceptionMessage fields

### ISSUE THREAD

**Issue by frankiedrake** [mp911de/logstash-gelf#290]
Hello, I've recently migrated to this library from [this](https://github.com/graylog-labs/log4j2-gelf) deprecated one and I've faced differences in how logs are now looking, some of them aren't significant but others are.

The main difference is there're no more fields, that allowed to distinguish the kind of an exception happened.
There was such useful fields In library I used before:
```
builder.additionalField("exceptionClass", thrown.getClass().getCanonicalName());
builder.additionalField("exceptionMessage", thrown.getMessage());
builder.additionalField("exceptionStackTrace", stackTrace);
```
Is it possible to enable this feature in one of the next releases? By default or by specifying some parameter, like "includeExceptionFields"

**Comment by mp911de** [comment]
Hey there. What logging framework are you using? If you use log4j2, then you can easily add custom fields through the config. 

Adding more fields affects every user of the library and that can easily break existing arrangements. A more suitable approach could be having a user-defined field contributor component that can provide more fields and values given the actual log event.
