### ISSUE TITLE
log4j 1.2.x Instructions on README Missing and Link Doesn't Go Anywhere

### ISSUE THREAD

**Issue by brileyd** [mp911de/logstash-gelf#295]
I noticed that there is a link on the readme file for log4j 1.2.x, but it doesn't go anywhere.  Also, I browsed the whole page, and it looks like there are no instructions for it either.

**Comment by mp911de** [comment]
Good catch, we missed to remove the link after updating the readme.

**Comment by mp911de** [comment]
doc
