### ISSUE TITLE
在log4j2的配置文件中可以支持引用环境变量或者bootstrap.properties(ctx)中的变量吗

### ISSUE THREAD

**Issue by VioletSY** [mp911de/logstash-gelf#296]
Make sure that:

- [ ] You have read the [contribution guidelines](https://github.com/mp911de/logstash-gelf/blob/master/.github/CONTRIBUTING.md).
- [ ] You specify the logstash-gelf version and environment so it's obvious which version is affected
- [ ] You provide a reproducible test case (either descriptive of as JUnit test) if it's a bug or the expected behavior differs from the actual behavior.

**Comment by mp911de** [comment]
This isn't an issue for this project as we accept the config provided by log4j2 and hand these details over to `PatternLayout`
