### ISSUE TITLE
logstash gelf input

### ISSUE THREAD

**Issue by karthiklml** [mp911de/logstash-gelf#40]
Hi, 
i am using graylog2 in my infra . i like to migrate to logstash . before proceeding that, i like to test a scenario's like 

gelf-input in logstash-shipper => MQ => logstash => kibana . this setup will work ? 

or the gelf modules are only for graylog output 
gelfinput in logstash-shipprt => graylog2-server => graylog2-web . 

i am trying the 1st option for testing and i am getting a parsing error . 

:message=>"Gelfd failed to parse a message skipping", :exception=>#, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/gelfd-0.2.0/lib/gelfd/parser.rb:14:in parse'", "/opt/logstash/lib/logstash/inputs/gelf.rb:83:inudp_listener'", "/opt/logstash/lib/logstash/inputs/gelf.rb:60:in run'", "/opt/logstash/lib/logstash/pipeline.rb:163:ininputworker'", "/opt/logstash/lib/logstash/pipeline.rb:157:in `start_input'"], :level=>:warn}

Please give your input . 

Thanks .

**Comment by mp911de** [comment]
Hello @karthiklml 
this scenario will (gelf-input in logstash-shipper => MQ => logstash **=> ElasticSearch** => kibana) work.  You forgot the ElasticSearch, since you need to store your data somewhere.

My logstash.conf looks like

```
input {
    gelf {
		port => 12201
		host => "::"
    }    
}
```

The reported bug indicates tampered UDP packets, see https://github.com/elasticsearch/logstash/issues/2116 for more details (this case had a loadbalancer which destroyed the UDP packages)

**Comment by karthiklml** [comment]
Hi Mark, 

Thanks for your response . 

input {
gelf {
host => "127.0.0.1"
port => 12201
type => "gelf"
}
}

filter {
}

output {
MQ details  
}

It can push the logs to MQ => Logstash-index-server => ES => kibana. 

But the error indicate it couldn't parse the data from the json input . And the data not going to MQ servers. It get dropped with the above error. could you please insight on my errors  

:message=>"Gelfd failed to parse a message skipping", :exception=>#, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/gelfd-0.2.0/lib/gelfd/parser.rb:14:in parse'", "/opt/logstash/lib/logstash/inputs/gelf.rb:83:inudp_listener'", "/opt/logstash/lib/logstash/inputs/gelf.rb:60:in run'", "/opt/logstash/lib/logstash/pipeline.rb:163:ininputworker'", "/opt/logstash/lib/logstash/pipeline.rb:157:in `start_input'"], :level=>:warn}

In my testing setup. i am only pushing the data from the command line . Hopefully no way the udp get tampered. 

Test input data is , 

echo '{"version": "1.1","host":"example.org","short_message":" what is going on","full_message":"Hello ","level":1,"_user_id":9001,"_some_info":"foo","_some_env_var":"bar"}' | nc -w 1 -u localhost 12201 

Am not sure what is the wrong in this . could you please guide me to fix this issue . 

Thanks .

**Comment by karthiklml** [comment]
When i updated the gelf.rb as per the reference link , i am getting the following error . 

Gelfd failed to parse a message skipping. Client was: ["AF_INET", 37816, "127.0.0.1", "127.0.0.1"] .Message was: "{\"version\": \"1.1\",\"host\":\"example.org\",\"short_message\":\"A short message that helps you identify what is going on\",\"full_message\":\"Backtrace here\\n\\nmore stuff\",\"level\":1,\"_user_id\":9001,\"_some_info\":\"foo\",\"_some_env_var\":\"bar\"}\n" {:exception=>#<Gelfd::UnknownHeaderError: Could not find parser for header: [123, 34]>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/gelfd-0.2.0/lib/gelfd/parser.rb:14:in `parse'", "/opt/logstash/lib/logstash/inputs/gelf.rb:83:in `udp_listener'", "/opt/logstash/lib/logstash/inputs/gelf.rb:60:in `run'", "/opt/logstash/lib/logstash/pipeline.rb:163:in `inputworker'", "/opt/logstash/lib/logstash/pipeline.rb:157:in `start_input'"], :level=>:warn}

**Comment by mp911de** [comment]
Give it a try using log4i, java.util.logging or logback. https://github.com/mp911de/logstash-gelf has some config examples. In general, I can provide you support when you use the Java GELF library. General logstash support can be found here: https://github.com/elasticsearch/logstash/issues

**Comment by mp911de** [comment]
Closing, no progress here.
