### ISSUE TITLE
logstash-gelf not sending all logs logged in catalina.out to remote logstash server

### ISSUE THREAD

**Issue by swethagaddam** [mp911de/logstash-gelf#44]
Hi,

I am using logstash-gelf appender in JULI to send tomcat logs to remote logstash server. I observed that in my catalina.out, some logs are in different format which are not being sent to logstash server.

In the below example, the first 2 logs in catalina.out which start with timestamp are sent to logstash and indexed in Elasticsearch, but the logs which start with log4j:WARN are not sent to logstash. Any idea what is the issue here? 

logs in catalina.out:

Apr 13, 2015 7:23:35 AM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://java.sun.com/jsp/jstl/fmt is already defined
Apr 13, 2015 7:23:35 AM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://java.sun.com/jsp/jstl/functions is already defined
log4j:WARN Continuable parsing error 9 and column 16
log4j:WARN The content of element type "appender" must match "(errorHandler?,param*,rollingPolicy?,triggeringPolicy?,connectionSource?,layout?,filter*,appender-ref*)".

**Comment by mp911de** [comment]
Hi @swethagaddam 
the issue with `catalina.out` is, that this is the complete sysout and syserr from the Tomcat Java process itself. If you take a look into `catalina.sh` or `catalina.bat` you'll find `>> "$CATALINA_OUT" 2>&1 "&"`

logstash-gelf is bound to a specific log framework, in your case JULI. The log4j messages are produced by log4j that is not configured for logstash-gelf (or at least it indicates a config error). If you want to capture __ALL__ sysout and syserr output, it might be better to listen with logstash/logstash forwarder on this specific file. 

HTH, Mark

**Comment by swethagaddam** [comment]
Thanks for your reply Mark!

>> If you want to capture ALL sysout and syserr output, it might be better to listen with logstash/logstash forwarder on this specific file.
If catalina.out file has different format of logs, it will be impossible to write parsers and extract all data into fields because the log message and stdout/stderr message would be in different formats in the same. Is there any way we can send stdout/stderr messages to ELK using logstash-gelf moduke?

Thanks
Swetha

**Comment by mp911de** [comment]
No, there is no chance. My approach is mostly capturing the output of the application only and ignoring the catalina.out. If you need the catalina.out, you could grab the output using logstash and ignoring the pattern. As long as you parse the logs in real-time, timestamp is not really an issue. You could use regex to determine the severity of the logs, but you're right, it's not nice.

You could also mix both patterns, so capturing the JULI part using logstash-gelf and also capturing the catalina.out but storing both in different indexes or tagging the records using fields (e.g. type=gelf and type=file).


In contrast to tomcat, JBoss provides a full log integration so no logs can bypass the loggers and will be fully captured using logstash-gelf.

**Comment by mp911de** [comment]
One more thing: You can use logstash-gelf for JUL, log4j, log4j2 and logback. Same library, different appender/handlers once it's on your classpath.

**Comment by mp911de** [comment]
Closing this issue since it seems resolved.
