### ISSUE TITLE
Extracted stacktrace is almost unreadable

### ISSUE THREAD

**Issue by yuriy-filatov** [mp911de/logstash-gelf#46]
I'm using Graylog v1.1.1 + GELF plugin v1.6.0,  ch.qos.logback from java app. I've enabled 'extractStackTrace' but graylog receives hardly readable unstructured stacktrace message, even if I enable 'filterStackTrace' option.
Looks like '\t' (or '\n', or both?) at the end of the line in stacktrace is lost somewhere.
Partial screenshot attached
![stacktrace](https://cloud.githubusercontent.com/assets/6918427/8135679/b9c00e7a-1141-11e5-9c36-a623ee9009af.JPG)

**Comment by mp911de** [comment]
An example JSON message under the GELF submission looks like 

```json
{"host":"...","_className":"biz.paluch.logging.gelf.log4j2.GelfLogAppenderNettyTcpTest",
"_StackTrace":"Exception: java.lang.Exception: test exception\n\tat biz.paluch.logging.gelf.log4j2.GelfLogAppenderNettyTcpTest.testSimpleInfo(GelfLogAppenderNettyTcpTest.java:64)\n\t\t21 lines skipped for [sun., java.lang.reflect.Method, org.junit]\n\tat com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)\n\tat com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)\n\tat com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)\n","_server.simple":"marks-mbp",
"full_message":"foo bar test log message",
"_timestamp":"12 Jun 2015 19:35:29,008",
"short_message":"foo bar test log message", ...}
```

The `_StackTrace` field contains `\t`'s and `\n`'s but I'm not sure, how Graylog handles them. It looks like, the line breaks are ignored because the content is converted to raw HTML or something like that. The same works for logstash/kibana very well, line breaks and tabs are indented the way they should be.

Did try other frameworks for the same issue?

**Comment by yuriy-filatov** [comment]
Tried pukkaone's - it doesn't have stacktrack part at all (or I overlooked that part in options).
Tried moocar - just dead right after launch.

Any hope that this can be fixed?

**Comment by mp911de** [comment]
I found an issue about the topic: https://github.com/Graylog2/graylog2-web-interface/issues/601 seems to be a config issue. I do not use Graylog in my projects.

**Comment by yuriy-filatov** [comment]
Thanks, gonna dig this issue there.
