### ISSUE TITLE
List on Graylog Marketplace

### ISSUE THREAD

**Issue by lennartkoopmann** [mp911de/logstash-gelf#53]
We have launched the beta of the Graylog Marketplace: https://marketplace.graylog.org/

The Marketplace is the central directory of all Graylog add-ons and integrations, including GELF libraries.

You would help us a lot if you could submit your GELF library there. :)

**Comment by mp911de** [comment]
Done. Thanks for the hint.

**Comment by lennartkoopmann** [comment]
Thank you! :+1: :shipit:
