### ISSUE TITLE
logstash-gelf-1.6.0-logging-module.zip doesn't contain WildFlyGelfLogHandler

### ISSUE THREAD

**Issue by marcuslinke** [mp911de/logstash-gelf#54]

**Comment by mp911de** [comment]
Hi @marcuslinke the `WildFlyGelfLogHandler` is shipped with 1.7 (see https://github.com/mp911de/logstash-gelf/issues/51). I'm awaiting the last tests from WF 10 before I can release the library.

Please use `JBoss7GelfLogHandler` in the mean time (see http://logging.paluch.biz/examples/jbossas7.html).

**Comment by marcuslinke** [comment]
Thanks for the hint! It works as expected now.

**Comment by mp911de** [comment]
Fixed by releasing 1.7.0
