### ISSUE TITLE
Use appropriate data type when parsing values from additional fields

### ISSUE THREAD

**Issue by kebers** [mp911de/logstash-gelf#56]
logstash-gelf converts any integer values in MDC fields into a double value with a floating point right before generating a JSON formatted GELF message based on those fields. 
example MDC Field (name,value):
"MyID": "1234" --> converted to --> "MyID":1234.0 

A query for [MyID: 1234] in Graylog v1.2.2 won't return any results, since the query is ignoring any entries with [MyID:1234.0] now. 
Graylog v1.0 was less exact on that and returned a result while Graylog v1.2.2 obviously is more strict.

logstash-gelf needs to pay attention on that as a matter of fact.
It should convert integer values appropriatly.

tested with application running on (source):
JBoss7 
WildFly 8.1

graylog versions (sink):
v1.0
v1.2.2

**Comment by mp911de** [comment]
Fixed.

**Comment by mp911de** [comment]
Released 1.7.2 to Maven central
