### ISSUE TITLE
RuntimeContainer.lookupHostname can take a REALLY long time.

### ISSUE THREAD

**Issue by DenEwout** [mp911de/logstash-gelf#58]
Hi,

I added gelf logging to a project of mine and noticed a considerable drop in performance. The project usually runs within a couple of seconds, but now it took about 15 seconds.

After some profiling and debugging I found that the lookupHostname method in RuntimeContainer takes a long time to process.

The reason for this is (as I understand it) this class goes over all network adapters in order to lookup a hostname. I have 3 network adapters (a USB/ethernet connection, WiFi and a virtual box Host-Only network adapter). Especially that last one took a long time with its hostname lookup (about 10 seconds).

I just set the logstash-gelf.skipHostnameResolution to true and was happy that I got my usual performance back.

Now here's my question: what purpose does hostname resolution serve? Can I just keep it disabled?

Kind Regards,

DenEwout

**Comment by mp911de** [comment]
Hi @DenEwout, 
the hostname resolution is a supportive feature if you don't specify the `originHost`. If you're not interested in the hostname for a particular case, then disable it. You can also specify a fixed host name or change the resolution order (network, local or local, network resolution order).

HTH, Mark

**Comment by DenEwout** [comment]
Thanks for the quick reply @mp911de :) Closed the issue.
