### ISSUE TITLE
Do not send source/location fields if source location is not available

### ISSUE THREAD

**Issue by jsmucr** [mp911de/logstash-gelf#67]
Log4j may show a question mark in place of a source code line number. This may lead to placing the question mark in the SourceLineNumber field and sending this **string** to the target server which -- if it expects an integer -- may not accept the message.

This issue appears when logging into an ElasticSearch backed software such as Graylog, because the fields within the database are created dynamically. If a string arrives, a string field is created for the current index and nothing can change that. If an integer arrives, an integer field is created and all messages containing a string value for this field end up being dropped and lost.

**Comment by mp911de** [comment]
Fixed.
