### ISSUE TITLE
Critical errors left out if configuration debug mode is not set (Logback)

### ISSUE THREAD

**Issue by salex89** [mp911de/logstash-gelf#69]
This is more of a logback thing than logstash-gelf, but I think worth noting. I don't know about other logging frameworks, but with Logback, if the `debug` attribute of the `configuration` element is set to `false` or ignored, internal appender errors are not shown. In case of logstash-gelf, invalid host or connectivity issues, will not be reported. 

Maybe it would be advisable to explicitly mention that in the `README.md`, since less experienced users may not find their way into debugging their issues and expect some output in the console.

**Comment by mp911de** [comment]
Done.
