### ISSUE TITLE
Unusable in mutlithreaded environment

### ISSUE THREAD

**Issue by Batigoal** [mp911de/logstash-gelf#70]
I tried to update to logstash-gelf 1.8.0 and all my async-tests in multithreaded environment fail.
Reason:
Your commit on January 4th on JUL GelfLogHandler (https://github.com/mp911de/logstash-gelf/commit/af5929038e1aa4ceaf229cc93488f4c5b01955a6#diff-e7d7cc92e345ef14a56f25696ace488e)  with the boolean publish - flag.
This causes Log-Messages to be discarded silently. In my tests, only 40 messages from 1000 (!!) are logged now. In our production environment we log about 5000-10000 Messages per second, and we didn't have any problem without this flag yet. In my opinion the synchronization/thread-handling has to be doen within the particular GelfSender (as i did in GelfRedisSender a while ago).

This problem also causes the new commit from jjungnickel (https://github.com/mp911de/logstash-gelf/commit/249106b8c63f34fa2033460c56b6f3febfa4522d#diff-e7d7cc92e345ef14a56f25696ace488e) . But synchronization on the jboss7-logger is not the solution, it only delays the problem (in our scnenario, synchronization on the logger is too slow!!).

So why does this happen?

Could you please revert this , otherwise this useful library isn't useable anymore for me :-(

**Comment by mp911de** [comment]
Hi @Batigoal 
the mentioned change is quite old (Jan 2015). The reason for that change was the Redis driver itself uses logging, and the change was to prevent recursive logger calls.

I agree the current solution is not the best solution. In fact, only the UDP appender _should_ be thread-safe, the TCP and Redis appenders are not thread-safe at all.

There are various ways how to approach this issue:
1. Synchronization in the sender, the approach you mentioned would work 
2. Create an abstraction layer for asynchronicity, basically, maintain a queue of events and decouple the event producing thread from the sending thread
3. Use the async facility from the logging framework you're using

All handlers for JUL I came across are synchronized on handler-level which seems to be the default pattern for JUL handlers.

I would like to do something about the synchronization issue and stay in touch with you to improve on the current state.

**Comment by Batigoal** [comment]
Hi!

My opinion to your suggestions:

1. "Synchronization in the sender, the approach you mentioned would work "
-> I think thats the way to go

2. "Create an abstraction layer for asynchronicity,"
-> That what I've done, but a single decoupled thread is not enough power, so I need mulithreading ( again to do my work 

3. "Use the async facility from the logging framework you're using"
May be this work, may be not. If they use the standard Logger in the async-szenario in the background (as I do AND e.g. the JBoss7-Logger does) then you'll have the problem again. See last commit, where the JBoss7-Logger publish-method has to be syncronized -> but in my opinion this should not be the solution

In my szenario I could not use this anymore, so maybe I have to write my own Logger/Appender because my (specific) sender implementations are threadsafe.

**Comment by mp911de** [comment]
Hi @Batigoal, 
I pushed a branch `issue/70-rework-handler-synchronization` with a refactored synchronization. Can you build the branch using `mvn clean install` and check whether the changes would work for you?

**Comment by Batigoal** [comment]
Hi!

Now it would work again! Thank you
But mention, that  I've only tested with my own (very special) sender-implementation.
I cannot verify the changes to your RedisGelfSender-implementation in my tests!

**Comment by mp911de** [comment]
Good to hear. I covered concurrency tests with the TCP/UDP senders.

**Comment by mp911de** [comment]
Fixed with 89d3840

**Comment by Batigoal** [comment]
Hi!

Could you please release a new version with this fix?

Thank you very much!

**Comment by mp911de** [comment]
I need to check what about #77 and then I'll create a new release, maybe Friday, Apr 15.

**Comment by mp911de** [comment]
1.9.0 is on it's way to Maven Central, should be synced in a few hours.
