### ISSUE TITLE
Boolean.getBoolean(String) requires a system property as input

### ISSUE THREAD

**Issue by slowjoe007** [mp911de/logstash-gelf#71]
In https://github.com/mp911de/logstash-gelf/blob/master/src/main/java/biz/paluch/logging/gelf/LogMessageField.java (line 114) method `verboseLog(String)` uses `java.lang.Boolean.getBoolean(String)` (https://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html#getBoolean%28java.lang.String%29) incorrectly. It takes the name of a system property, but here it is passed the strings `true` or `false` only... this won't work. Use `java.lang.Boolean.parseBoolean(String)`instead.

**Comment by slowjoe007** [comment]
Besides that the result of the system property lookup should be cached to spend less time parsing strings.

**Comment by mp911de** [comment]
Thanks, that's fixed.
