### ISSUE TITLE
Uncompressed gelf output

### ISSUE THREAD

**Issue by callmegar** [mp911de/logstash-gelf#72]
Is it possible to send output uncompressed/unencoded/raw, I'm trying to write straight to splunk but need the messages on plain JSON

**Comment by mp911de** [comment]
Not today. Maybe a dedicated JSON logger/formatter would do the job since most logger frameworks have a built-in JSON formatter which can be used with a `SocketAppender`.

**Comment by mp911de** [comment]
Update: You can use JSON output with the TCP and Redis appenders.

**Comment by mp911de** [comment]
Closing this ticket, no further activity.
