### ISSUE TITLE
Using AsyncLogger causing class being empty 

### ISSUE THREAD

**Issue by DaveTaboola** [mp911de/logstash-gelf#74]
Hi 
I've been verifying this case for the past couple of days 
I've found that using Async loggers is causing gelf sending the class parameter as "?" instead of the full class as expected and as it works with sync logger

did anyone else bumped into this issue?

**Comment by mp911de** [comment]
Hi Dave, 
which logging framework do you use? log4j 1/2? logback?

**Comment by DaveTaboola** [comment]
Log4j2

**Comment by mp911de** [comment]
Hi @DaveTaboola, 

please make sure to set the `includeLocation` property to `true` when using async loggers:

```
<AsyncLogger name="async.location" level="trace" includeLocation="true">
        <AppenderRef ref="gelf"/>
</AsyncLogger>
```

See [log4j2-async-netty-tcp.xml](https://github.com/mp911de/logstash-gelf/blob/master/src/test/resources/log4j2/log4j2-async-netty-tcp.xml) for a complete example.

**Comment by DaveTaboola** [comment]
@mp911de that was the trick! 
Thank you so much for the help and for the great work with the gelf appender! 
you rock! :D
