### ISSUE TITLE
InetAddress cached

### ISSUE THREAD

**Issue by sergiomahs** [mp911de/logstash-gelf#77]
Whenever the first log is sent, the variable hostname is cached in GelfTCPSender. If for example the graylog server is in the cloud and the ip changes, the hostname won't be the correct one anymore, so it has to be recalculated again.

Our workaround is to find the hostname  everytime that a log is appended and the Socket is null.

`protected Socket createSocket() throws IOException {
		Socket socket = new Socket();
		socket.setSoTimeout(readTimeoutMs);
		socket.setKeepAlive(keepAlive);
		InetAddress hostname = InetAddress.getByName(host);
		socket.connect(new InetSocketAddress(hostname, port), connectTimeoutMs);
		return socket;
	}`

**Comment by mp911de** [comment]
Works only with the TCP/Redis-senders as UDP has no connection state.

**Comment by mp911de** [comment]
Fixed. I'll release 1.9.0 tomorrow (Apr 15).

**Comment by kirrmann** [comment]
Sorry for digging up this old issue. But the issue seems to be still valid for the UDP sender. Could you please fix this too?

**Comment by mp911de** [comment]
@kirrmann UDP has no notion of connection. In any case, `GelfUDPSender` creates a new `InetSocketAddress` if an `IOException` happens.

https://github.com/mp911de/logstash-gelf/blob/master/src/main/java/biz/paluch/logging/gelf/intern/sender/GelfUDPSender.java#L91

**Comment by kirrmann** [comment]
Sorry my fault. I only took a look at the code of version 1.7.0, which is the one I'm using. But you're right, in the current version it should work and try to resolve again.
