### ISSUE TITLE
Rethrow Exceptions in log4j2 GelfLogAppender

### ISSUE THREAD

**Issue by swimmesberger** [mp911de/logstash-gelf#78]
The log4j2 GelfLogAppender silently logs the exceptions which happen (even for "trivial" errors like a failed connection to the server (TCP)). Stuff like FailoverAppender from log4j2 relies on exceptions thrown by the primary appender to resort back to the secondary appenders. FailoverAppender therefore can't be used in conjunction with the GelfLogAppender. Log4j2 default appender use a flag called "ignoreExceptions" which can be passed to the AbstractAppender. The default behaviour in log4j2 is to simply throw all errors which happen while appending with a "org.apache.logging.log4j.core.appender.AppenderLoggingException". When the ignoreExceptions flag is true all errors are catched and simply logged with the DefaultErrorHandler in the AbstractAppender class when the flag is false all errors bubble up and can therefore be used by appender like the FailoverAppender to do something else with the LogEvent in case of an error.

Version: 1.8.1

**Comment by mp911de** [comment]
Good catch! Errors are reported to `org.apache.logging.log4j.status.StatusLogger` but `ignoreExceptions ` is not used to rethrow exceptions. It's possible to rethrow exceptions if `ignoreExceptions` is set to `false`. That change won't break existing code since `ignoreExceptions` defaults to `true`.

**Comment by mp911de** [comment]
Fixed with 0d6af73cf6e0562c20f28ce554bfb0660fdc8e09.
