### ISSUE TITLE
Make "facility" field optional

### ISSUE THREAD

**Issue by swimmesberger** [mp911de/logstash-gelf#79]
I'm using "logstash-gelf" in conjunction with log42j. According to the GELF spec* the "facility" field is optional (and deprecated) but it's not really possible to remove the field from the GelfMessage. When I explicitly make the field emtpy the resulting GelfMessage is not valid** anymore which results in a exception thrown in the log4j2 GelfLoggingAppender,

\* http://docs.graylog.org/en/latest/pages/gelf.html
\*\* https://github.com/mp911de/logstash-gelf/blob/master/src/main/java/biz/paluch/logging/gelf/intern/GelfMessage.java#L402)

Version: 1.8.1

**Comment by mp911de** [comment]
Thanks for the ticket. I'll include that change in 1.9.1

**Comment by mp911de** [comment]
Done.
