### ISSUE TITLE
Make jedis and commons-pool2 dependencies optional

### ISSUE THREAD

**Issue by mp911de** [mp911de/logstash-gelf#80]
The `jedis` Redis driver is marked as mandatory compile dependency in the pom.xml. The driver is not needed at runtime when not using Redis. Switch the dependency to `<optional>true</optional>` but make sure the dependency is still packaged in the distribution files.

**Comment by psh-tc** [comment]
Futhermore the redis libs introduce a detecting dependency convergence which should be fixed.

When including the latest logstash-gelf version (1.9) in our project the maven enforcer plugin reports the folling error:

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability the error(s) are [
Dependency convergence error for org.apache.commons:commons-pool2:2.3 paths to dependency are:
+-xxx
  +-biz.paluch.logging:logstash-gelf:1.9.0
    +-redis.clients:jedis:2.8.0
      +-org.apache.commons:commons-pool2:2.3
and
+-xxx
  +-biz.paluch.logging:logstash-gelf:1.9.0
    +-org.apache.commons:commons-pool2:2.4.2
]

**Comment by mp911de** [comment]
Thanks @psh-tc, will fix that, too.

**Comment by mp911de** [comment]
`commons-pool2` version issue fixed by raising Jedis to 2.8.1 which requires `commons-pool2` 2.4.2
