### ISSUE TITLE
JulLogEvent does not translate bundle messages if no parameter is supplied

### ISSUE THREAD

**Issue by matthiasblaesing** [mp911de/logstash-gelf#82]
We were evaluating logstash and logstash-gelf as the adapter to tie our application servers (glassfish/payara) into the logging system. Glassfish/Payara uses java.util.logging as its logging system and so the GelfLogHandler was configured as described.

While checking the logging I noticed differences between the log file and the log entries from the GELF stream. I could track this case down to the usage of bundle messages, that are for example used by the metro integration in glassfish. So while the logfile got the translated/expanded message, the GELF stream only contained the bundle keys.

JulLogEvent#createMessage does the bundle key lookup in line 70. This line is only reached, if parameters are present (at least one) - line 68. Moving the translation outside the if-statement should fix that (move lines 69-71 out of the if block between 67 and 68.

Thanks!

**Comment by mp911de** [comment]
Hi @matthiasblaesing 
thanks for the ticket. Do you want to submit a PR or should I fix the issue?
