### ISSUE TITLE
Feature request: Add an option to turn off GELF compression

### ISSUE THREAD

**Issue by jsmucr** [mp911de/logstash-gelf#85]
Graylog does not support compressed log messages received through the Kafka input and drops them.

**Comment by mp911de** [comment]
GZIP Compression is only available on UDP. Not sure which role Kafka plays here. Could you pls elaborate?

**Comment by jsmucr** [comment]
My use case is this: I collect log data from various points including many Java apps and as the amount of logs started growing, any Graylog downtime has become an issue. So I decided to prepend a Kafka instance to it (another Graylog instance might be a solution but not as cheap). To keep the monitored apps' configuration the same, I use a udp-kafka bridge listening on 12201/udp. So far so good and it works well. But for plain text GELFs only. The rest ends up dropped.

**Comment by mp911de** [comment]
Thanks a lot. I think the best approach is to specify the option in the host field, similar to [TCP](http://logging.paluch.biz/tcp.html) and [Redis](http://logging.paluch.biz/redis.html) which takes a query-string approach.

```
udp:hostname?compression=false
```

The default would be:

```
udp:hostname?compression=gzip
```

**Comment by cchet** [comment]
I this still an issue, would like to help out?

**Comment by mp911de** [comment]
Thanks @cchet. I assume from ticket activity that there are not many users that would need such a feature. This is a good moment to close it. It does not make sense to build and maintain a feature no one needs.

**Comment by jsmucr** [comment]
I originally needed the feature to be able to send logs via Kafka but I eventually worked it around. Thank you for the software anyway, it's priceless. :-)
