### ISSUE TITLE
Tomcat access log via logstash-gelf， how to add extend field，like linux env or string.

### ISSUE THREAD

**Issue by halcyonone** [mp911de/logstash-gelf#93]
my tomcat server.xml config:

```
<Valve className="biz.paluch.logging.accesslogvalve.GelfAccessLogValve"
                        host="redis://127.0.0.1:6379#tomcat_access" port="12201"
               pattern="%{yyyy.MM.dd HH:mm:ss}t %h &quot;%r&quot; %s %b &quot;%{Referer}i&quot; &quot;%{User-Agent}i&quot; &quot;%{X-Forwarded-For}i&quot; %Dms; fund-www &quot;"
               resolveHosts="false"
               />
```

how to add extend field, like linux env or other k/v? thank you.

**Comment by mp911de** [comment]
[`GelfAccessLogValve`](https://gist.github.com/mp911de/c558d1bc48effe4844e2) is not a class that is part of a released library, it was a proposal how one could implement access log forwarding using logstash-gelf.

This means you're free in adding additional fields inside the class and the XML config. You can add custom data to a message using `GelfMessage#addField(String key, String value)`, also pull data from system properties (`System.getProperty("os.version")`) or env variables. That's up to you.

The only thing you need is Java coding skills and a compiler.

**Comment by mp911de** [comment]
Closing this ticket, seems answered since lack of further activity.
