### ISSUE TITLE
How to configure the Glassfish/Payara?

### ISSUE THREAD

**Issue by zemiak** [mp911de/logstash-gelf#94]
Hello,

how to make Glassfishuse this custom log appender(java.util.logging via logging.properties). Where should I put the lib, so it's recognized by Glassfish as a custom log appender?

Currently, it seems to be ignored in both GF/glassfish/lib and GF/glassfish/modules

Thanks,
Miro

**Comment by mp911de** [comment]
Hi, 
I have zero experience with Glassfish so I fear I can't help you with this one. There seem to be some documentation around custom loggers and Glassfish. Maybe you ask Google or in Glassfish/Payara forums.

Feel free to open a ticket if you run into issues with logstash-gelf and Glassfish when logstash-gelf is properly installed.

**Comment by zemiak** [comment]
Maybe you would want to update the docs. In Glassfish/Payara, you have to copy the JUL appender (including needed libraries) in the glassfish/domains/{yourdomain}/lib/ext/ folder.

**Comment by mp911de** [comment]
Thanks for the hint. I'll update the documentation accordingly.
