### ISSUE TITLE
Add TLS support for TCP sender

### ISSUE THREAD

**Issue by mp911de** [mp911de/logstash-gelf#95]
Add support to use a secure transport channel when using TCP. The protocol scheme could be one of `tls://`, `tcps://`, `ssl://` or `tcp+ssl://`.

**Comment by reynold-lariza** [comment]
Hey guys,

I'm looking for this. having the impression that TLS/SSL has been implemented, is this working now? and how do I add it?

Thanks,

**Comment by mp911de** [comment]
That's fixed since 2016, see the docs at https://logging.paluch.biz/tcp.html for further details.
